/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.mundipagg.api.models.*;
import com.mundipagg.api.exceptions.*;
import com.mundipagg.api.APIHelper;
import com.mundipagg.api.DateTimeHelper;
import com.mundipagg.api.Configuration;
import com.mundipagg.api.testing.TestHelper;
import com.mundipagg.api.controllers.RecipientsController;

import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

public class RecipientsControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static RecipientsController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getRecipients();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Retrieves paginated recipients information
     * @throws Throwable
     */
    @Test
    public void testTestGetRecipients() throws Throwable {
        // Parameters for the API call
        Integer page = null;
        Integer size = null;

        // Set callback and perform API call
        RecipientsResponse result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getRecipients(page, size);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

    }

}
