/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class ApplePayBuilder {
    //the instance to build
    private ApplePay applePay;

    /**
     * Default constructor to initialize the instance
     */
    public ApplePayBuilder() {
        applePay = new ApplePay();
    }

    /**
     * The token version
     */
    public ApplePayBuilder version(String version) {
        applePay.setVersion(version);
        return this;
    }

    /**
     * The cryptography data
     */
    public ApplePayBuilder data(String data) {
        applePay.setData(data);
        return this;
    }

    public ApplePayBuilder header(Header header) {
        applePay.setHeader(header);
        return this;
    }

    /**
     * Detached PKCS #7 signature, Base64 encoded as string
     */
    public ApplePayBuilder signature(String signature) {
        applePay.setSignature(signature);
        return this;
    }

    /**
     * ApplePay Merchant identifier
     */
    public ApplePayBuilder merchantIdentifier(String merchantIdentifier) {
        applePay.setMerchantIdentifier(merchantIdentifier);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApplePay build() {
        return applePay;
    }
}