/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class AuthenticationBuilder {
    //the instance to build
    private Authentication authentication;

    /**
     * Default constructor to initialize the instance
     */
    public AuthenticationBuilder() {
        authentication = new Authentication();
    }

    public AuthenticationBuilder type(String type) {
        authentication.setType(type);
        return this;
    }

    public AuthenticationBuilder threedSecure(ThreedSecure threedSecure) {
        authentication.setThreedSecure(threedSecure);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Authentication build() {
        return authentication;
    }
}