/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class BankTransfer1Builder {
    //the instance to build
    private BankTransfer1 bankTransfer1;

    /**
     * Default constructor to initialize the instance
     */
    public BankTransfer1Builder() {
        bankTransfer1 = new BankTransfer1();
    }

    /**
     * Bank
     */
    public BankTransfer1Builder bank(String bank) {
        bankTransfer1.setBank(bank);
        return this;
    }

    /**
     * Number of retries
     */
    public BankTransfer1Builder retries(int retries) {
        bankTransfer1.setRetries(retries);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BankTransfer1 build() {
        return bankTransfer1;
    }
}