/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class BankTransfer2Builder {
    //the instance to build
    private BankTransfer2 bankTransfer2;

    /**
     * Default constructor to initialize the instance
     */
    public BankTransfer2Builder() {
        bankTransfer2 = new BankTransfer2();
    }

    /**
     * Bank
     */
    public BankTransfer2Builder bank(List<String> bank) {
        bankTransfer2.setBank(bank);
        return this;
    }

    /**
     * Number of retries for processing
     */
    public BankTransfer2Builder retries(int retries) {
        bankTransfer2.setRetries(retries);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BankTransfer2 build() {
        return bankTransfer2;
    }
}