/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class BillingAddressBuilder {
    //the instance to build
    private BillingAddress billingAddress;

    /**
     * Default constructor to initialize the instance
     */
    public BillingAddressBuilder() {
        billingAddress = new BillingAddress();
    }

    public BillingAddressBuilder street(String street) {
        billingAddress.setStreet(street);
        return this;
    }

    public BillingAddressBuilder number(String number) {
        billingAddress.setNumber(number);
        return this;
    }

    public BillingAddressBuilder zipCode(String zipCode) {
        billingAddress.setZipCode(zipCode);
        return this;
    }

    public BillingAddressBuilder neighborhood(String neighborhood) {
        billingAddress.setNeighborhood(neighborhood);
        return this;
    }

    public BillingAddressBuilder city(String city) {
        billingAddress.setCity(city);
        return this;
    }

    public BillingAddressBuilder state(String state) {
        billingAddress.setState(state);
        return this;
    }

    public BillingAddressBuilder country(String country) {
        billingAddress.setCountry(country);
        return this;
    }

    public BillingAddressBuilder complement(String complement) {
        billingAddress.setComplement(complement);
        return this;
    }

    /**
     * Line 1 for address
     */
    public BillingAddressBuilder line1(String line1) {
        billingAddress.setLine1(line1);
        return this;
    }

    /**
     * Line 2 for address
     */
    public BillingAddressBuilder line2(String line2) {
        billingAddress.setLine2(line2);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BillingAddress build() {
        return billingAddress;
    }
}