/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class BillingAddress1Builder {
    //the instance to build
    private BillingAddress1 billingAddress1;

    /**
     * Default constructor to initialize the instance
     */
    public BillingAddress1Builder() {
        billingAddress1 = new BillingAddress1();
    }

    /**
     * Street
     */
    public BillingAddress1Builder street(String street) {
        billingAddress1.setStreet(street);
        return this;
    }

    /**
     * Number
     */
    public BillingAddress1Builder number(String number) {
        billingAddress1.setNumber(number);
        return this;
    }

    /**
     * The zip code containing only numbers. No special characters or spaces.
     */
    public BillingAddress1Builder zipCode(String zipCode) {
        billingAddress1.setZipCode(zipCode);
        return this;
    }

    /**
     * Neighborhood
     */
    public BillingAddress1Builder neighborhood(String neighborhood) {
        billingAddress1.setNeighborhood(neighborhood);
        return this;
    }

    /**
     * City
     */
    public BillingAddress1Builder city(String city) {
        billingAddress1.setCity(city);
        return this;
    }

    /**
     * State
     */
    public BillingAddress1Builder state(String state) {
        billingAddress1.setState(state);
        return this;
    }

    /**
     * Country. Must be entered using ISO 3166-1 alpha-2 format. See https://pt.wikipedia.org/wiki/ISO_3166-1_alfa-2
     */
    public BillingAddress1Builder country(String country) {
        billingAddress1.setCountry(country);
        return this;
    }

    /**
     * Complement
     */
    public BillingAddress1Builder complement(String complement) {
        billingAddress1.setComplement(complement);
        return this;
    }

    /**
     * Metadata
     */
    public BillingAddress1Builder metadata(LinkedHashMap<String, String> metadata) {
        billingAddress1.setMetadata(metadata);
        return this;
    }

    /**
     * Line 1 for address
     */
    public BillingAddress1Builder line1(String line1) {
        billingAddress1.setLine1(line1);
        return this;
    }

    /**
     * Line 2 for address
     */
    public BillingAddress1Builder line2(String line2) {
        billingAddress1.setLine2(line2);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BillingAddress1 build() {
        return billingAddress1;
    }
}