/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class Boleto1Builder {
    //the instance to build
    private Boleto1 boleto1;

    /**
     * Default constructor to initialize the instance
     */
    public Boleto1Builder() {
        boleto1 = new Boleto1();
    }

    /**
     * Number of retries
     */
    public Boleto1Builder retries(int retries) {
        boleto1.setRetries(retries);
        return this;
    }

    /**
     * The bank code, containing three characters. The available codes are on the API specification
     */
    public Boleto1Builder bank(String bank) {
        boleto1.setBank(bank);
        return this;
    }

    /**
     * The instructions field that will be printed on the boleto.
     */
    public Boleto1Builder instructions(String instructions) {
        boleto1.setInstructions(instructions);
        return this;
    }

    /**
     * Boleto due date
     */
    public Boleto1Builder dueAt(DateTime dueAt) {
        boleto1.setDueAt(dueAt);
        return this;
    }

    public Boleto1Builder billingAddress(BillingAddress1 billingAddress) {
        boleto1.setBillingAddress(billingAddress);
        return this;
    }

    /**
     * The address id for the billing address
     */
    public Boleto1Builder billingAddressId(String billingAddressId) {
        boleto1.setBillingAddressId(billingAddressId);
        return this;
    }

    /**
     * Customer identification number with the bank
     */
    public Boleto1Builder nossoNumero(String nossoNumero) {
        boleto1.setNossoNumero(nossoNumero);
        return this;
    }

    /**
     * Boleto identification
     */
    public Boleto1Builder documentNumber(String documentNumber) {
        boleto1.setDocumentNumber(documentNumber);
        return this;
    }

    public Boleto1Builder interest(Interest interest) {
        boleto1.setInterest(interest);
        return this;
    }

    public Boleto1Builder fine(Fine fine) {
        boleto1.setFine(fine);
        return this;
    }

    public Boleto1Builder maxDaysToPayPastDue(Integer maxDaysToPayPastDue) {
        boleto1.setMaxDaysToPayPastDue(maxDaysToPayPastDue);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Boleto1 build() {
        return boleto1;
    }
}