/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CancelSplitRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8283823946649634516L;
    private String type;
    private int amount;
    private String recipientId;
    private Options2 options;
    private String splitRuleId;
    /** GETTER
     * Split type
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Split type
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Amount
     */
    @JsonGetter("amount")
    public int getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * Amount
     */
    @JsonSetter("amount")
    public void setAmount (int value) { 
        this.amount = value;
    }
 
    /** GETTER
     * Recipient id
     */
    @JsonGetter("recipient_id")
    public String getRecipientId ( ) { 
        return this.recipientId;
    }
    
    /** SETTER
     * Recipient id
     */
    @JsonSetter("recipient_id")
    public void setRecipientId (String value) { 
        this.recipientId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("options")
    public Options2 getOptions ( ) { 
        return this.options;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("options")
    public void setOptions (Options2 value) { 
        this.options = value;
    }
 
    /** GETTER
     * Rule id
     */
    @JsonGetter("split_rule_id")
    public String getSplitRuleId ( ) { 
        return this.splitRuleId;
    }
    
    /** SETTER
     * Rule id
     */
    @JsonSetter("split_rule_id")
    public void setSplitRuleId (String value) { 
        this.splitRuleId = value;
    }
 
}
