/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class ChargesMetadataResponseBuilder {
    //the instance to build
    private ChargesMetadataResponse chargesMetadataResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ChargesMetadataResponseBuilder() {
        chargesMetadataResponse = new ChargesMetadataResponse();
    }

    public ChargesMetadataResponseBuilder id(String id) {
        chargesMetadataResponse.setId(id);
        return this;
    }

    public ChargesMetadataResponseBuilder code(String code) {
        chargesMetadataResponse.setCode(code);
        return this;
    }

    public ChargesMetadataResponseBuilder gatewayId(String gatewayId) {
        chargesMetadataResponse.setGatewayId(gatewayId);
        return this;
    }

    public ChargesMetadataResponseBuilder amount(int amount) {
        chargesMetadataResponse.setAmount(amount);
        return this;
    }

    public ChargesMetadataResponseBuilder status(String status) {
        chargesMetadataResponse.setStatus(status);
        return this;
    }

    public ChargesMetadataResponseBuilder currency(String currency) {
        chargesMetadataResponse.setCurrency(currency);
        return this;
    }

    public ChargesMetadataResponseBuilder paymentMethod(String paymentMethod) {
        chargesMetadataResponse.setPaymentMethod(paymentMethod);
        return this;
    }

    public ChargesMetadataResponseBuilder dueAt(DateTime dueAt) {
        chargesMetadataResponse.setDueAt(dueAt);
        return this;
    }

    public ChargesMetadataResponseBuilder createdAt(DateTime createdAt) {
        chargesMetadataResponse.setCreatedAt(createdAt);
        return this;
    }

    public ChargesMetadataResponseBuilder updatedAt(DateTime updatedAt) {
        chargesMetadataResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public ChargesMetadataResponseBuilder lastTransaction(GetTransactionResponse lastTransaction) {
        chargesMetadataResponse.setLastTransaction(lastTransaction);
        return this;
    }

    public ChargesMetadataResponseBuilder invoice(Invoice invoice) {
        chargesMetadataResponse.setInvoice(invoice);
        return this;
    }

    public ChargesMetadataResponseBuilder order(Order order) {
        chargesMetadataResponse.setOrder(order);
        return this;
    }

    public ChargesMetadataResponseBuilder customer(Customer customer) {
        chargesMetadataResponse.setCustomer(customer);
        return this;
    }

    public ChargesMetadataResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        chargesMetadataResponse.setMetadata(metadata);
        return this;
    }

    public ChargesMetadataResponseBuilder paidAt(DateTime paidAt) {
        chargesMetadataResponse.setPaidAt(paidAt);
        return this;
    }

    public ChargesMetadataResponseBuilder canceledAt(DateTime canceledAt) {
        chargesMetadataResponse.setCanceledAt(canceledAt);
        return this;
    }

    /**
     * Canceled Amount
     */
    public ChargesMetadataResponseBuilder canceledAmount(int canceledAmount) {
        chargesMetadataResponse.setCanceledAmount(canceledAmount);
        return this;
    }

    /**
     * Paid amount
     */
    public ChargesMetadataResponseBuilder paidAmount(int paidAmount) {
        chargesMetadataResponse.setPaidAmount(paidAmount);
        return this;
    }

    /**
     * Defines whether the card has been used one or more times.
     */
    public ChargesMetadataResponseBuilder recurrencyCycle(String recurrencyCycle) {
        chargesMetadataResponse.setRecurrencyCycle(recurrencyCycle);
        return this;
    }

    /**
     * interest and fine paid
     */
    public ChargesMetadataResponseBuilder interestAndFinePaid(Integer interestAndFinePaid) {
        chargesMetadataResponse.setInterestAndFinePaid(interestAndFinePaid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChargesMetadataResponse build() {
        return chargesMetadataResponse;
    }
}