/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class ChargesRequestBuilder {
    //the instance to build
    private ChargesRequest chargesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ChargesRequestBuilder() {
        chargesRequest = new ChargesRequest();
    }

    /**
     * The amount that will be canceled.
     */
    public ChargesRequestBuilder amount(Integer amount) {
        chargesRequest.setAmount(amount);
        return this;
    }

    /**
     * The split rules request
     */
    public ChargesRequestBuilder splitRules(List<CreateCancelChargeSplitRulesRequest> splitRules) {
        chargesRequest.setSplitRules(splitRules);
        return this;
    }

    /**
     * Splits
     */
    public ChargesRequestBuilder split(List<CreateSplitRequest> split) {
        chargesRequest.setSplit(split);
        return this;
    }

    public ChargesRequestBuilder operationReference(String operationReference) {
        chargesRequest.setOperationReference(operationReference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChargesRequest build() {
        return chargesRequest;
    }
}