/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class ChargesDueDateRequestBuilder {
    //the instance to build
    private ChargesDueDateRequest chargesDueDateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ChargesDueDateRequestBuilder() {
        chargesDueDateRequest = new ChargesDueDateRequest();
    }

    /**
     * The charge's new due date
     */
    public ChargesDueDateRequestBuilder dueAt(DateTime dueAt) {
        chargesDueDateRequest.setDueAt(dueAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChargesDueDateRequest build() {
        return chargesDueDateRequest;
    }
}