/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CreatePaymentRequestBuilder {
    //the instance to build
    private CreatePaymentRequest createPaymentRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreatePaymentRequestBuilder() {
        createPaymentRequest = new CreatePaymentRequest();
    }

    /**
     * Payment method
     */
    public CreatePaymentRequestBuilder paymentMethod(String paymentMethod) {
        createPaymentRequest.setPaymentMethod(paymentMethod);
        return this;
    }

    public CreatePaymentRequestBuilder creditCard(CreditCard1 creditCard) {
        createPaymentRequest.setCreditCard(creditCard);
        return this;
    }

    public CreatePaymentRequestBuilder debitCard(DebitCard1 debitCard) {
        createPaymentRequest.setDebitCard(debitCard);
        return this;
    }

    public CreatePaymentRequestBuilder boleto(Boleto1 boleto) {
        createPaymentRequest.setBoleto(boleto);
        return this;
    }

    /**
     * Currency. Must be informed using 3 characters
     */
    public CreatePaymentRequestBuilder currency(String currency) {
        createPaymentRequest.setCurrency(currency);
        return this;
    }

    public CreatePaymentRequestBuilder voucher(Voucher voucher) {
        createPaymentRequest.setVoucher(voucher);
        return this;
    }

    /**
     * Splits
     */
    public CreatePaymentRequestBuilder split(List<CreateSplitRequest> split) {
        createPaymentRequest.setSplit(split);
        return this;
    }

    public CreatePaymentRequestBuilder bankTransfer(BankTransfer1 bankTransfer) {
        createPaymentRequest.setBankTransfer(bankTransfer);
        return this;
    }

    /**
     * Gateway affiliation code
     */
    public CreatePaymentRequestBuilder gatewayAffiliationId(String gatewayAffiliationId) {
        createPaymentRequest.setGatewayAffiliationId(gatewayAffiliationId);
        return this;
    }

    /**
     * The amount of the payment, in cents
     */
    public CreatePaymentRequestBuilder amount(Integer amount) {
        createPaymentRequest.setAmount(amount);
        return this;
    }

    public CreatePaymentRequestBuilder checkout(Checkout checkout) {
        createPaymentRequest.setCheckout(checkout);
        return this;
    }

    /**
     * Customer Id
     */
    public CreatePaymentRequestBuilder customerId(String customerId) {
        createPaymentRequest.setCustomerId(customerId);
        return this;
    }

    public CreatePaymentRequestBuilder customer(Customer8 customer) {
        createPaymentRequest.setCustomer(customer);
        return this;
    }

    /**
     * Metadata
     */
    public CreatePaymentRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        createPaymentRequest.setMetadata(metadata);
        return this;
    }

    public CreatePaymentRequestBuilder cash(CreateCashPaymentRequest cash) {
        createPaymentRequest.setCash(cash);
        return this;
    }

    public CreatePaymentRequestBuilder privateLabel(PrivateLabel privateLabel) {
        createPaymentRequest.setPrivateLabel(privateLabel);
        return this;
    }

    public CreatePaymentRequestBuilder pix(Pix pix) {
        createPaymentRequest.setPix(pix);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatePaymentRequest build() {
        return createPaymentRequest;
    }
}