/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersCardsRequestBuilder {
    //the instance to build
    private CustomersCardsRequest customersCardsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersCardsRequestBuilder() {
        customersCardsRequest = new CustomersCardsRequest();
    }

    /**
     * Credit card number
     */
    public CustomersCardsRequestBuilder number(String number) {
        customersCardsRequest.setNumber(number);
        return this;
    }

    /**
     * Holder name, as written on the card
     */
    public CustomersCardsRequestBuilder holderName(String holderName) {
        customersCardsRequest.setHolderName(holderName);
        return this;
    }

    /**
     * The expiration month
     */
    public CustomersCardsRequestBuilder expMonth(int expMonth) {
        customersCardsRequest.setExpMonth(expMonth);
        return this;
    }

    /**
     * The expiration year, that can be informed with 2 or 4 digits
     */
    public CustomersCardsRequestBuilder expYear(int expYear) {
        customersCardsRequest.setExpYear(expYear);
        return this;
    }

    /**
     * The card's security code
     */
    public CustomersCardsRequestBuilder cvv(String cvv) {
        customersCardsRequest.setCvv(cvv);
        return this;
    }

    public CustomersCardsRequestBuilder billingAddress(BillingAddress1 billingAddress) {
        customersCardsRequest.setBillingAddress(billingAddress);
        return this;
    }

    /**
     * Card brand
     */
    public CustomersCardsRequestBuilder brand(String brand) {
        customersCardsRequest.setBrand(brand);
        return this;
    }

    /**
     * The address id for the billing address
     */
    public CustomersCardsRequestBuilder billingAddressId(String billingAddressId) {
        customersCardsRequest.setBillingAddressId(billingAddressId);
        return this;
    }

    /**
     * Metadata
     */
    public CustomersCardsRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        customersCardsRequest.setMetadata(metadata);
        return this;
    }

    /**
     * Card type
     */
    public CustomersCardsRequestBuilder type(String type) {
        customersCardsRequest.setType(type);
        return this;
    }

    public CustomersCardsRequestBuilder options(Options1 options) {
        customersCardsRequest.setOptions(options);
        return this;
    }

    /**
     * Document number for the card's holder
     */
    public CustomersCardsRequestBuilder holderDocument(String holderDocument) {
        customersCardsRequest.setHolderDocument(holderDocument);
        return this;
    }

    /**
     * Indicates whether it is a private label card
     */
    public CustomersCardsRequestBuilder privateLabel(boolean privateLabel) {
        customersCardsRequest.setPrivateLabel(privateLabel);
        return this;
    }

    public CustomersCardsRequestBuilder label(String label) {
        customersCardsRequest.setLabel(label);
        return this;
    }

    /**
     * Identifier
     */
    public CustomersCardsRequestBuilder id(String id) {
        customersCardsRequest.setId(id);
        return this;
    }

    /**
     * token identifier
     */
    public CustomersCardsRequestBuilder token(String token) {
        customersCardsRequest.setToken(token);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersCardsRequest build() {
        return customersCardsRequest;
    }
}