/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CustomersCardsRenewResponseBuilder {
    //the instance to build
    private CustomersCardsRenewResponse customersCardsRenewResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersCardsRenewResponseBuilder() {
        customersCardsRenewResponse = new CustomersCardsRenewResponse();
    }

    public CustomersCardsRenewResponseBuilder id(String id) {
        customersCardsRenewResponse.setId(id);
        return this;
    }

    public CustomersCardsRenewResponseBuilder lastFourDigits(String lastFourDigits) {
        customersCardsRenewResponse.setLastFourDigits(lastFourDigits);
        return this;
    }

    public CustomersCardsRenewResponseBuilder brand(String brand) {
        customersCardsRenewResponse.setBrand(brand);
        return this;
    }

    public CustomersCardsRenewResponseBuilder holderName(String holderName) {
        customersCardsRenewResponse.setHolderName(holderName);
        return this;
    }

    public CustomersCardsRenewResponseBuilder expMonth(int expMonth) {
        customersCardsRenewResponse.setExpMonth(expMonth);
        return this;
    }

    public CustomersCardsRenewResponseBuilder expYear(int expYear) {
        customersCardsRenewResponse.setExpYear(expYear);
        return this;
    }

    public CustomersCardsRenewResponseBuilder status(String status) {
        customersCardsRenewResponse.setStatus(status);
        return this;
    }

    public CustomersCardsRenewResponseBuilder createdAt(DateTime createdAt) {
        customersCardsRenewResponse.setCreatedAt(createdAt);
        return this;
    }

    public CustomersCardsRenewResponseBuilder updatedAt(DateTime updatedAt) {
        customersCardsRenewResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public CustomersCardsRenewResponseBuilder billingAddress(BillingAddress billingAddress) {
        customersCardsRenewResponse.setBillingAddress(billingAddress);
        return this;
    }

    public CustomersCardsRenewResponseBuilder customer(Customer customer) {
        customersCardsRenewResponse.setCustomer(customer);
        return this;
    }

    public CustomersCardsRenewResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        customersCardsRenewResponse.setMetadata(metadata);
        return this;
    }

    /**
     * Card type
     */
    public CustomersCardsRenewResponseBuilder type(String type) {
        customersCardsRenewResponse.setType(type);
        return this;
    }

    /**
     * Document number for the card's holder
     */
    public CustomersCardsRenewResponseBuilder holderDocument(String holderDocument) {
        customersCardsRenewResponse.setHolderDocument(holderDocument);
        return this;
    }

    public CustomersCardsRenewResponseBuilder deletedAt(DateTime deletedAt) {
        customersCardsRenewResponse.setDeletedAt(deletedAt);
        return this;
    }

    /**
     * First six digits
     */
    public CustomersCardsRenewResponseBuilder firstSixDigits(String firstSixDigits) {
        customersCardsRenewResponse.setFirstSixDigits(firstSixDigits);
        return this;
    }

    public CustomersCardsRenewResponseBuilder label(String label) {
        customersCardsRenewResponse.setLabel(label);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersCardsRenewResponse build() {
        return customersCardsRenewResponse;
    }
}