/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersAddressesRequestBuilder {
    //the instance to build
    private CustomersAddressesRequest customersAddressesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAddressesRequestBuilder() {
        customersAddressesRequest = new CustomersAddressesRequest();
    }

    /**
     * Street
     */
    public CustomersAddressesRequestBuilder street(String street) {
        customersAddressesRequest.setStreet(street);
        return this;
    }

    /**
     * Number
     */
    public CustomersAddressesRequestBuilder number(String number) {
        customersAddressesRequest.setNumber(number);
        return this;
    }

    /**
     * The zip code containing only numbers. No special characters or spaces.
     */
    public CustomersAddressesRequestBuilder zipCode(String zipCode) {
        customersAddressesRequest.setZipCode(zipCode);
        return this;
    }

    /**
     * Neighborhood
     */
    public CustomersAddressesRequestBuilder neighborhood(String neighborhood) {
        customersAddressesRequest.setNeighborhood(neighborhood);
        return this;
    }

    /**
     * City
     */
    public CustomersAddressesRequestBuilder city(String city) {
        customersAddressesRequest.setCity(city);
        return this;
    }

    /**
     * State
     */
    public CustomersAddressesRequestBuilder state(String state) {
        customersAddressesRequest.setState(state);
        return this;
    }

    /**
     * Country. Must be entered using ISO 3166-1 alpha-2 format. See https://pt.wikipedia.org/wiki/ISO_3166-1_alfa-2
     */
    public CustomersAddressesRequestBuilder country(String country) {
        customersAddressesRequest.setCountry(country);
        return this;
    }

    /**
     * Complement
     */
    public CustomersAddressesRequestBuilder complement(String complement) {
        customersAddressesRequest.setComplement(complement);
        return this;
    }

    /**
     * Metadata
     */
    public CustomersAddressesRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        customersAddressesRequest.setMetadata(metadata);
        return this;
    }

    /**
     * Line 1 for address
     */
    public CustomersAddressesRequestBuilder line1(String line1) {
        customersAddressesRequest.setLine1(line1);
        return this;
    }

    /**
     * Line 2 for address
     */
    public CustomersAddressesRequestBuilder line2(String line2) {
        customersAddressesRequest.setLine2(line2);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAddressesRequest build() {
        return customersAddressesRequest;
    }
}