/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersMetadataRequestBuilder {
    //the instance to build
    private CustomersMetadataRequest customersMetadataRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersMetadataRequestBuilder() {
        customersMetadataRequest = new CustomersMetadataRequest();
    }

    /**
     * Metadata
     */
    public CustomersMetadataRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        customersMetadataRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersMetadataRequest build() {
        return customersMetadataRequest;
    }
}