/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersCardsRequest1Builder {
    //the instance to build
    private CustomersCardsRequest1 customersCardsRequest1;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersCardsRequest1Builder() {
        customersCardsRequest1 = new CustomersCardsRequest1();
    }

    /**
     * Holder name
     */
    public CustomersCardsRequest1Builder holderName(String holderName) {
        customersCardsRequest1.setHolderName(holderName);
        return this;
    }

    /**
     * Expiration month
     */
    public CustomersCardsRequest1Builder expMonth(int expMonth) {
        customersCardsRequest1.setExpMonth(expMonth);
        return this;
    }

    /**
     * Expiration year
     */
    public CustomersCardsRequest1Builder expYear(int expYear) {
        customersCardsRequest1.setExpYear(expYear);
        return this;
    }

    /**
     * Id of the address to be used as billing address
     */
    public CustomersCardsRequest1Builder billingAddressId(String billingAddressId) {
        customersCardsRequest1.setBillingAddressId(billingAddressId);
        return this;
    }

    public CustomersCardsRequest1Builder billingAddress(BillingAddress1 billingAddress) {
        customersCardsRequest1.setBillingAddress(billingAddress);
        return this;
    }

    /**
     * Metadata
     */
    public CustomersCardsRequest1Builder metadata(LinkedHashMap<String, String> metadata) {
        customersCardsRequest1.setMetadata(metadata);
        return this;
    }

    public CustomersCardsRequest1Builder label(String label) {
        customersCardsRequest1.setLabel(label);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersCardsRequest1 build() {
        return customersCardsRequest1;
    }
}