/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersAccessTokensRequestBuilder {
    //the instance to build
    private CustomersAccessTokensRequest customersAccessTokensRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAccessTokensRequestBuilder() {
        customersAccessTokensRequest = new CustomersAccessTokensRequest();
    }

    /**
     * Minutes to expire the token
     */
    public CustomersAccessTokensRequestBuilder expiresIn(Integer expiresIn) {
        customersAccessTokensRequest.setExpiresIn(expiresIn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAccessTokensRequest build() {
        return customersAccessTokensRequest;
    }
}