/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CustomerBuilder {
    //the instance to build
    private Customer customer;

    /**
     * Default constructor to initialize the instance
     */
    public CustomerBuilder() {
        customer = new Customer();
    }

    public CustomerBuilder id(String id) {
        customer.setId(id);
        return this;
    }

    public CustomerBuilder name(String name) {
        customer.setName(name);
        return this;
    }

    public CustomerBuilder email(String email) {
        customer.setEmail(email);
        return this;
    }

    public CustomerBuilder delinquent(boolean delinquent) {
        customer.setDelinquent(delinquent);
        return this;
    }

    public CustomerBuilder createdAt(DateTime createdAt) {
        customer.setCreatedAt(createdAt);
        return this;
    }

    public CustomerBuilder updatedAt(DateTime updatedAt) {
        customer.setUpdatedAt(updatedAt);
        return this;
    }

    public CustomerBuilder document(String document) {
        customer.setDocument(document);
        return this;
    }

    public CustomerBuilder type(String type) {
        customer.setType(type);
        return this;
    }

    public CustomerBuilder fbAccessToken(String fbAccessToken) {
        customer.setFbAccessToken(fbAccessToken);
        return this;
    }

    public CustomerBuilder address(Address address) {
        customer.setAddress(address);
        return this;
    }

    public CustomerBuilder metadata(LinkedHashMap<String, String> metadata) {
        customer.setMetadata(metadata);
        return this;
    }

    public CustomerBuilder phones(GetPhonesResponse phones) {
        customer.setPhones(phones);
        return this;
    }

    public CustomerBuilder fbId(Long fbId) {
        customer.setFbId(fbId);
        return this;
    }

    /**
     * Código de referência do cliente no sistema da loja. Max: 52 caracteres
     */
    public CustomerBuilder code(String code) {
        customer.setCode(code);
        return this;
    }

    public CustomerBuilder documentType(String documentType) {
        customer.setDocumentType(documentType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Customer build() {
        return customer;
    }
}