/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CustomersAccessTokensResponseBuilder {
    //the instance to build
    private CustomersAccessTokensResponse customersAccessTokensResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAccessTokensResponseBuilder() {
        customersAccessTokensResponse = new CustomersAccessTokensResponse();
    }

    public CustomersAccessTokensResponseBuilder id(String id) {
        customersAccessTokensResponse.setId(id);
        return this;
    }

    public CustomersAccessTokensResponseBuilder code(String code) {
        customersAccessTokensResponse.setCode(code);
        return this;
    }

    public CustomersAccessTokensResponseBuilder status(String status) {
        customersAccessTokensResponse.setStatus(status);
        return this;
    }

    public CustomersAccessTokensResponseBuilder createdAt(DateTime createdAt) {
        customersAccessTokensResponse.setCreatedAt(createdAt);
        return this;
    }

    public CustomersAccessTokensResponseBuilder customer(Customer customer) {
        customersAccessTokensResponse.setCustomer(customer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAccessTokensResponse build() {
        return customersAccessTokensResponse;
    }
}