/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersAddressesRequest1Builder {
    //the instance to build
    private CustomersAddressesRequest1 customersAddressesRequest1;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAddressesRequest1Builder() {
        customersAddressesRequest1 = new CustomersAddressesRequest1();
    }

    /**
     * Number
     */
    public CustomersAddressesRequest1Builder number(String number) {
        customersAddressesRequest1.setNumber(number);
        return this;
    }

    /**
     * Complement
     */
    public CustomersAddressesRequest1Builder complement(String complement) {
        customersAddressesRequest1.setComplement(complement);
        return this;
    }

    /**
     * Metadata
     */
    public CustomersAddressesRequest1Builder metadata(LinkedHashMap<String, String> metadata) {
        customersAddressesRequest1.setMetadata(metadata);
        return this;
    }

    /**
     * Line 2 for address
     */
    public CustomersAddressesRequest1Builder line2(String line2) {
        customersAddressesRequest1.setLine2(line2);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAddressesRequest1 build() {
        return customersAddressesRequest1;
    }
}