/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CustomersResponseBuilder {
    //the instance to build
    private CustomersResponse customersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersResponseBuilder() {
        customersResponse = new CustomersResponse();
    }

    public CustomersResponseBuilder id(String id) {
        customersResponse.setId(id);
        return this;
    }

    public CustomersResponseBuilder name(String name) {
        customersResponse.setName(name);
        return this;
    }

    public CustomersResponseBuilder email(String email) {
        customersResponse.setEmail(email);
        return this;
    }

    public CustomersResponseBuilder delinquent(boolean delinquent) {
        customersResponse.setDelinquent(delinquent);
        return this;
    }

    public CustomersResponseBuilder createdAt(DateTime createdAt) {
        customersResponse.setCreatedAt(createdAt);
        return this;
    }

    public CustomersResponseBuilder updatedAt(DateTime updatedAt) {
        customersResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public CustomersResponseBuilder document(String document) {
        customersResponse.setDocument(document);
        return this;
    }

    public CustomersResponseBuilder type(String type) {
        customersResponse.setType(type);
        return this;
    }

    public CustomersResponseBuilder fbAccessToken(String fbAccessToken) {
        customersResponse.setFbAccessToken(fbAccessToken);
        return this;
    }

    public CustomersResponseBuilder address(Address address) {
        customersResponse.setAddress(address);
        return this;
    }

    public CustomersResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        customersResponse.setMetadata(metadata);
        return this;
    }

    public CustomersResponseBuilder phones(GetPhonesResponse phones) {
        customersResponse.setPhones(phones);
        return this;
    }

    public CustomersResponseBuilder fbId(Long fbId) {
        customersResponse.setFbId(fbId);
        return this;
    }

    /**
     * Código de referência do cliente no sistema da loja. Max: 52 caracteres
     */
    public CustomersResponseBuilder code(String code) {
        customersResponse.setCode(code);
        return this;
    }

    public CustomersResponseBuilder documentType(String documentType) {
        customersResponse.setDocumentType(documentType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersResponse build() {
        return customersResponse;
    }
}