/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersCardsResponse1Builder {
    //the instance to build
    private CustomersCardsResponse1 customersCardsResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersCardsResponse1Builder() {
        customersCardsResponse1 = new CustomersCardsResponse1();
    }

    /**
     * The card objects
     */
    public CustomersCardsResponse1Builder data(List<GetCardResponse> data) {
        customersCardsResponse1.setData(data);
        return this;
    }

    public CustomersCardsResponse1Builder paging(Paging paging) {
        customersCardsResponse1.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersCardsResponse1 build() {
        return customersCardsResponse1;
    }
}