/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CustomersResponse3 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4762341139568284360L;
    private List<GetCustomerResponse> data;
    private Paging paging;
    /** GETTER
     * The customer object
     */
    @JsonGetter("data")
    public List<GetCustomerResponse> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * The customer object
     */
    @JsonSetter("data")
    public void setData (List<GetCustomerResponse> value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paging")
    public Paging getPaging ( ) { 
        return this.paging;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paging")
    public void setPaging (Paging value) { 
        this.paging = value;
    }
 
}
