/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersAccessTokensResponse1Builder {
    //the instance to build
    private CustomersAccessTokensResponse1 customersAccessTokensResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAccessTokensResponse1Builder() {
        customersAccessTokensResponse1 = new CustomersAccessTokensResponse1();
    }

    /**
     * The access token objects
     */
    public CustomersAccessTokensResponse1Builder data(List<GetAccessTokenResponse> data) {
        customersAccessTokensResponse1.setData(data);
        return this;
    }

    public CustomersAccessTokensResponse1Builder paging(Paging paging) {
        customersAccessTokensResponse1.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAccessTokensResponse1 build() {
        return customersAccessTokensResponse1;
    }
}