/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class CustomersAddressesResponseBuilder {
    //the instance to build
    private CustomersAddressesResponse customersAddressesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CustomersAddressesResponseBuilder() {
        customersAddressesResponse = new CustomersAddressesResponse();
    }

    /**
     * The address objects
     */
    public CustomersAddressesResponseBuilder data(List<GetAddressResponse> data) {
        customersAddressesResponse.setData(data);
        return this;
    }

    public CustomersAddressesResponseBuilder paging(Paging paging) {
        customersAddressesResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomersAddressesResponse build() {
        return customersAddressesResponse;
    }
}