/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CycleBuilder {
    //the instance to build
    private Cycle cycleInstance;

    /**
     * Default constructor to initialize the instance
     */
    public CycleBuilder() {
        cycleInstance = new Cycle();
    }

    public CycleBuilder startAt(DateTime startAt) {
        cycleInstance.setStartAt(startAt);
        return this;
    }

    public CycleBuilder endAt(DateTime endAt) {
        cycleInstance.setEndAt(endAt);
        return this;
    }

    public CycleBuilder id(String id) {
        cycleInstance.setId(id);
        return this;
    }

    public CycleBuilder billingAt(DateTime billingAt) {
        cycleInstance.setBillingAt(billingAt);
        return this;
    }

    public CycleBuilder subscription(GetSubscriptionResponse subscription) {
        cycleInstance.setSubscription(subscription);
        return this;
    }

    public CycleBuilder status(String status) {
        cycleInstance.setStatus(status);
        return this;
    }

    public CycleBuilder duration(int duration) {
        cycleInstance.setDuration(duration);
        return this;
    }

    public CycleBuilder createdAt(String createdAt) {
        cycleInstance.setCreatedAt(createdAt);
        return this;
    }

    public CycleBuilder updatedAt(String updatedAt) {
        cycleInstance.setUpdatedAt(updatedAt);
        return this;
    }

    public CycleBuilder cycle(int cycle) {
        cycleInstance.setCycle(cycle);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Cycle build() {
        return cycleInstance;
    }
}