/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class DebitCard2Builder {
    //the instance to build
    private DebitCard2 debitCard2;

    /**
     * Default constructor to initialize the instance
     */
    public DebitCard2Builder() {
        debitCard2 = new DebitCard2();
    }

    /**
     * Card invoice text descriptor
     */
    public DebitCard2Builder statementDescriptor(String statementDescriptor) {
        debitCard2.setStatementDescriptor(statementDescriptor);
        return this;
    }

    public DebitCard2Builder authentication(Authentication2 authentication) {
        debitCard2.setAuthentication(authentication);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DebitCard2 build() {
        return debitCard2;
    }
}