/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class Device1Builder {
    //the instance to build
    private Device1 device1;

    /**
     * Default constructor to initialize the instance
     */
    public Device1Builder() {
        device1 = new Device1();
    }

    /**
     * Device's platform
     */
    public Device1Builder platform(String platform) {
        device1.setPlatform(platform);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Device1 build() {
        return device1;
    }
}