/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class FineBuilder {
    //the instance to build
    private Fine fine;

    /**
     * Default constructor to initialize the instance
     */
    public FineBuilder() {
        fine = new Fine();
    }

    /**
     * Days
     */
    public FineBuilder days(int days) {
        fine.setDays(days);
        return this;
    }

    /**
     * Type
     */
    public FineBuilder type(String type) {
        fine.setType(type);
        return this;
    }

    /**
     * Amount
     */
    public FineBuilder amount(int amount) {
        fine.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Fine build() {
        return fine;
    }
}