/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetAnticipationLimitsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6798452558780747815L;
    private Max max;
    private Min min;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("max")
    public Max getMax ( ) { 
        return this.max;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("max")
    public void setMax (Max value) { 
        this.max = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("min")
    public Min getMin ( ) { 
        return this.min;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("min")
    public void setMin (Min value) { 
        this.min = value;
    }
 
}
