/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetPaymentAuthenticationResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6482822797301144640L;
    private String type;
    private ThreedSecure threedSecure;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("threed_secure")
    public ThreedSecure getThreedSecure ( ) { 
        return this.threedSecure;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("threed_secure")
    public void setThreedSecure (ThreedSecure value) { 
        this.threedSecure = value;
    }
 
}
