/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetUsagesDetailsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5396469850550889461L;
    private String subscriptionId;
    private int totalAmount;
    private Period period;
    private Usages usages;
    private Integer totalDiscount;
    private Integer totalIncrement;
    /** GETTER
     * Subscription Identifier
     */
    @JsonGetter("subscription_id")
    public String getSubscriptionId ( ) { 
        return this.subscriptionId;
    }
    
    /** SETTER
     * Subscription Identifier
     */
    @JsonSetter("subscription_id")
    public void setSubscriptionId (String value) { 
        this.subscriptionId = value;
    }
 
    /** GETTER
     * Current Invoice Amount
     */
    @JsonGetter("total_amount")
    public int getTotalAmount ( ) { 
        return this.totalAmount;
    }
    
    /** SETTER
     * Current Invoice Amount
     */
    @JsonSetter("total_amount")
    public void setTotalAmount (int value) { 
        this.totalAmount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Period")
    public Period getPeriod ( ) { 
        return this.period;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Period")
    public void setPeriod (Period value) { 
        this.period = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Usages")
    public Usages getUsages ( ) { 
        return this.usages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Usages")
    public void setUsages (Usages value) { 
        this.usages = value;
    }
 
    /** GETTER
     * Total discounted value
     */
    @JsonGetter("total_discount")
    public Integer getTotalDiscount ( ) { 
        return this.totalDiscount;
    }
    
    /** SETTER
     * Total discounted value
     */
    @JsonSetter("total_discount")
    public void setTotalDiscount (Integer value) { 
        this.totalDiscount = value;
    }
 
    /** GETTER
     * Total inremented value
     */
    @JsonGetter("total_increment")
    public Integer getTotalIncrement ( ) { 
        return this.totalIncrement;
    }
    
    /** SETTER
     * Total inremented value
     */
    @JsonSetter("total_increment")
    public void setTotalIncrement (Integer value) { 
        this.totalIncrement = value;
    }
 
}
