/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GooglePay 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8815052726900693668L;
    private String version;
    private String data;
    private Header1 header;
    private String signature;
    private String merchantIdentifier;
    /** GETTER
     * The token version
     */
    @JsonGetter("version")
    public String getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * The token version
     */
    @JsonSetter("version")
    public void setVersion (String value) { 
        this.version = value;
    }
 
    /** GETTER
     * The cryptography data
     */
    @JsonGetter("data")
    public String getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * The cryptography data
     */
    @JsonSetter("data")
    public void setData (String value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("header")
    public Header1 getHeader ( ) { 
        return this.header;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("header")
    public void setHeader (Header1 value) { 
        this.header = value;
    }
 
    /** GETTER
     * Detached PKCS #7 signature, Base64 encoded as string
     */
    @JsonGetter("signature")
    public String getSignature ( ) { 
        return this.signature;
    }
    
    /** SETTER
     * Detached PKCS #7 signature, Base64 encoded as string
     */
    @JsonSetter("signature")
    public void setSignature (String value) { 
        this.signature = value;
    }
 
    /** GETTER
     * GooglePay Merchant identifier
     */
    @JsonGetter("merchant_identifier")
    public String getMerchantIdentifier ( ) { 
        return this.merchantIdentifier;
    }
    
    /** SETTER
     * GooglePay Merchant identifier
     */
    @JsonSetter("merchant_identifier")
    public void setMerchantIdentifier (String value) { 
        this.merchantIdentifier = value;
    }
 
}
