/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class Header1Builder {
    //the instance to build
    private Header1 header1;

    /**
     * Default constructor to initialize the instance
     */
    public Header1Builder() {
        header1 = new Header1();
    }

    /**
     * X.509 encoded key bytes, Base64 encoded as a string
     */
    public Header1Builder ephemeralPublicKey(String ephemeralPublicKey) {
        header1.setEphemeralPublicKey(ephemeralPublicKey);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Header1 build() {
        return header1;
    }
}