/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class InvoicesResponse2Builder {
    //the instance to build
    private InvoicesResponse2 invoicesResponse2;

    /**
     * Default constructor to initialize the instance
     */
    public InvoicesResponse2Builder() {
        invoicesResponse2 = new InvoicesResponse2();
    }

    /**
     * The Invoice objects
     */
    public InvoicesResponse2Builder data(List<GetInvoiceResponse> data) {
        invoicesResponse2.setData(data);
        return this;
    }

    public InvoicesResponse2Builder paging(Paging paging) {
        invoicesResponse2.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InvoicesResponse2 build() {
        return invoicesResponse2;
    }
}