/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class InvoicesStatusResponseBuilder {
    //the instance to build
    private InvoicesStatusResponse invoicesStatusResponse;

    /**
     * Default constructor to initialize the instance
     */
    public InvoicesStatusResponseBuilder() {
        invoicesStatusResponse = new InvoicesStatusResponse();
    }

    public InvoicesStatusResponseBuilder id(String id) {
        invoicesStatusResponse.setId(id);
        return this;
    }

    public InvoicesStatusResponseBuilder code(String code) {
        invoicesStatusResponse.setCode(code);
        return this;
    }

    public InvoicesStatusResponseBuilder url(String url) {
        invoicesStatusResponse.setUrl(url);
        return this;
    }

    public InvoicesStatusResponseBuilder amount(int amount) {
        invoicesStatusResponse.setAmount(amount);
        return this;
    }

    public InvoicesStatusResponseBuilder status(String status) {
        invoicesStatusResponse.setStatus(status);
        return this;
    }

    public InvoicesStatusResponseBuilder paymentMethod(String paymentMethod) {
        invoicesStatusResponse.setPaymentMethod(paymentMethod);
        return this;
    }

    public InvoicesStatusResponseBuilder createdAt(DateTime createdAt) {
        invoicesStatusResponse.setCreatedAt(createdAt);
        return this;
    }

    public InvoicesStatusResponseBuilder items(List<GetInvoiceItemResponse> items) {
        invoicesStatusResponse.setItems(items);
        return this;
    }

    public InvoicesStatusResponseBuilder customer(Customer customer) {
        invoicesStatusResponse.setCustomer(customer);
        return this;
    }

    public InvoicesStatusResponseBuilder charge(Charge charge) {
        invoicesStatusResponse.setCharge(charge);
        return this;
    }

    public InvoicesStatusResponseBuilder installments(int installments) {
        invoicesStatusResponse.setInstallments(installments);
        return this;
    }

    public InvoicesStatusResponseBuilder billingAddress(BillingAddress billingAddress) {
        invoicesStatusResponse.setBillingAddress(billingAddress);
        return this;
    }

    public InvoicesStatusResponseBuilder subscription(GetSubscriptionResponse subscription) {
        invoicesStatusResponse.setSubscription(subscription);
        return this;
    }

    public InvoicesStatusResponseBuilder cycle(Cycle cycle) {
        invoicesStatusResponse.setCycle(cycle);
        return this;
    }

    public InvoicesStatusResponseBuilder shipping(Shipping shipping) {
        invoicesStatusResponse.setShipping(shipping);
        return this;
    }

    public InvoicesStatusResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        invoicesStatusResponse.setMetadata(metadata);
        return this;
    }

    public InvoicesStatusResponseBuilder dueAt(DateTime dueAt) {
        invoicesStatusResponse.setDueAt(dueAt);
        return this;
    }

    public InvoicesStatusResponseBuilder canceledAt(DateTime canceledAt) {
        invoicesStatusResponse.setCanceledAt(canceledAt);
        return this;
    }

    public InvoicesStatusResponseBuilder billingAt(DateTime billingAt) {
        invoicesStatusResponse.setBillingAt(billingAt);
        return this;
    }

    public InvoicesStatusResponseBuilder seenAt(DateTime seenAt) {
        invoicesStatusResponse.setSeenAt(seenAt);
        return this;
    }

    /**
     * Total discounted value
     */
    public InvoicesStatusResponseBuilder totalDiscount(Integer totalDiscount) {
        invoicesStatusResponse.setTotalDiscount(totalDiscount);
        return this;
    }

    /**
     * Total discounted value
     */
    public InvoicesStatusResponseBuilder totalIncrement(Integer totalIncrement) {
        invoicesStatusResponse.setTotalIncrement(totalIncrement);
        return this;
    }

    /**
     * Subscription Id
     */
    public InvoicesStatusResponseBuilder subscriptionId(String subscriptionId) {
        invoicesStatusResponse.setSubscriptionId(subscriptionId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InvoicesStatusResponse build() {
        return invoicesStatusResponse;
    }
}