/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class InvoicesResponseBuilder {
    //the instance to build
    private InvoicesResponse invoicesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public InvoicesResponseBuilder() {
        invoicesResponse = new InvoicesResponse();
    }

    public InvoicesResponseBuilder id(String id) {
        invoicesResponse.setId(id);
        return this;
    }

    public InvoicesResponseBuilder code(String code) {
        invoicesResponse.setCode(code);
        return this;
    }

    public InvoicesResponseBuilder url(String url) {
        invoicesResponse.setUrl(url);
        return this;
    }

    public InvoicesResponseBuilder amount(int amount) {
        invoicesResponse.setAmount(amount);
        return this;
    }

    public InvoicesResponseBuilder status(String status) {
        invoicesResponse.setStatus(status);
        return this;
    }

    public InvoicesResponseBuilder paymentMethod(String paymentMethod) {
        invoicesResponse.setPaymentMethod(paymentMethod);
        return this;
    }

    public InvoicesResponseBuilder createdAt(DateTime createdAt) {
        invoicesResponse.setCreatedAt(createdAt);
        return this;
    }

    public InvoicesResponseBuilder items(List<GetInvoiceItemResponse> items) {
        invoicesResponse.setItems(items);
        return this;
    }

    public InvoicesResponseBuilder customer(Customer customer) {
        invoicesResponse.setCustomer(customer);
        return this;
    }

    public InvoicesResponseBuilder charge(Charge charge) {
        invoicesResponse.setCharge(charge);
        return this;
    }

    public InvoicesResponseBuilder installments(int installments) {
        invoicesResponse.setInstallments(installments);
        return this;
    }

    public InvoicesResponseBuilder billingAddress(BillingAddress billingAddress) {
        invoicesResponse.setBillingAddress(billingAddress);
        return this;
    }

    public InvoicesResponseBuilder subscription(GetSubscriptionResponse subscription) {
        invoicesResponse.setSubscription(subscription);
        return this;
    }

    public InvoicesResponseBuilder cycle(Cycle cycle) {
        invoicesResponse.setCycle(cycle);
        return this;
    }

    public InvoicesResponseBuilder shipping(Shipping shipping) {
        invoicesResponse.setShipping(shipping);
        return this;
    }

    public InvoicesResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        invoicesResponse.setMetadata(metadata);
        return this;
    }

    public InvoicesResponseBuilder dueAt(DateTime dueAt) {
        invoicesResponse.setDueAt(dueAt);
        return this;
    }

    public InvoicesResponseBuilder canceledAt(DateTime canceledAt) {
        invoicesResponse.setCanceledAt(canceledAt);
        return this;
    }

    public InvoicesResponseBuilder billingAt(DateTime billingAt) {
        invoicesResponse.setBillingAt(billingAt);
        return this;
    }

    public InvoicesResponseBuilder seenAt(DateTime seenAt) {
        invoicesResponse.setSeenAt(seenAt);
        return this;
    }

    /**
     * Total discounted value
     */
    public InvoicesResponseBuilder totalDiscount(Integer totalDiscount) {
        invoicesResponse.setTotalDiscount(totalDiscount);
        return this;
    }

    /**
     * Total discounted value
     */
    public InvoicesResponseBuilder totalIncrement(Integer totalIncrement) {
        invoicesResponse.setTotalIncrement(totalIncrement);
        return this;
    }

    /**
     * Subscription Id
     */
    public InvoicesResponseBuilder subscriptionId(String subscriptionId) {
        invoicesResponse.setSubscriptionId(subscriptionId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InvoicesResponse build() {
        return invoicesResponse;
    }
}