/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class ListSubscriptionsResponseBuilder {
    //the instance to build
    private ListSubscriptionsResponse listSubscriptionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListSubscriptionsResponseBuilder() {
        listSubscriptionsResponse = new ListSubscriptionsResponse();
    }

    /**
     * The subscription objects
     */
    public ListSubscriptionsResponseBuilder data(List<GetSubscriptionResponse> data) {
        listSubscriptionsResponse.setData(data);
        return this;
    }

    public ListSubscriptionsResponseBuilder paging(Paging paging) {
        listSubscriptionsResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListSubscriptionsResponse build() {
        return listSubscriptionsResponse;
    }
}