/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class MaxBuilder {
    //the instance to build
    private Max max;

    /**
     * Default constructor to initialize the instance
     */
    public MaxBuilder() {
        max = new Max();
    }

    /**
     * Amount
     */
    public MaxBuilder amount(int amount) {
        max.setAmount(amount);
        return this;
    }

    /**
     * Anticipation fee
     */
    public MaxBuilder anticipationFee(int anticipationFee) {
        max.setAnticipationFee(anticipationFee);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Max build() {
        return max;
    }
}