/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class Options2Builder {
    //the instance to build
    private Options2 options2;

    /**
     * Default constructor to initialize the instance
     */
    public Options2Builder() {
        options2 = new Options2();
    }

    /**
     * Liable options
     */
    public Options2Builder liable(Boolean liable) {
        options2.setLiable(liable);
        return this;
    }

    /**
     * Charge processing fee
     */
    public Options2Builder chargeProcessingFee(Boolean chargeProcessingFee) {
        options2.setChargeProcessingFee(chargeProcessingFee);
        return this;
    }

    public Options2Builder chargeRemainderFee(Boolean chargeRemainderFee) {
        options2.setChargeRemainderFee(chargeRemainderFee);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Options2 build() {
        return options2;
    }
}