/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class OrdersResponseBuilder {
    //the instance to build
    private OrdersResponse ordersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public OrdersResponseBuilder() {
        ordersResponse = new OrdersResponse();
    }

    /**
     * The order object
     */
    public OrdersResponseBuilder data(List<GetOrderResponse> data) {
        ordersResponse.setData(data);
        return this;
    }

    public OrdersResponseBuilder paging(Paging paging) {
        ordersResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OrdersResponse build() {
        return ordersResponse;
    }
}