/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class OrdersClosedResponseBuilder {
    //the instance to build
    private OrdersClosedResponse ordersClosedResponse;

    /**
     * Default constructor to initialize the instance
     */
    public OrdersClosedResponseBuilder() {
        ordersClosedResponse = new OrdersClosedResponse();
    }

    public OrdersClosedResponseBuilder id(String id) {
        ordersClosedResponse.setId(id);
        return this;
    }

    public OrdersClosedResponseBuilder code(String code) {
        ordersClosedResponse.setCode(code);
        return this;
    }

    public OrdersClosedResponseBuilder currency(String currency) {
        ordersClosedResponse.setCurrency(currency);
        return this;
    }

    public OrdersClosedResponseBuilder items(List<GetOrderItemResponse> items) {
        ordersClosedResponse.setItems(items);
        return this;
    }

    public OrdersClosedResponseBuilder customer(Customer customer) {
        ordersClosedResponse.setCustomer(customer);
        return this;
    }

    public OrdersClosedResponseBuilder status(String status) {
        ordersClosedResponse.setStatus(status);
        return this;
    }

    public OrdersClosedResponseBuilder createdAt(DateTime createdAt) {
        ordersClosedResponse.setCreatedAt(createdAt);
        return this;
    }

    public OrdersClosedResponseBuilder updatedAt(DateTime updatedAt) {
        ordersClosedResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public OrdersClosedResponseBuilder charges(List<GetChargeResponse> charges) {
        ordersClosedResponse.setCharges(charges);
        return this;
    }

    public OrdersClosedResponseBuilder invoiceUrl(String invoiceUrl) {
        ordersClosedResponse.setInvoiceUrl(invoiceUrl);
        return this;
    }

    public OrdersClosedResponseBuilder shipping(Shipping shipping) {
        ordersClosedResponse.setShipping(shipping);
        return this;
    }

    public OrdersClosedResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        ordersClosedResponse.setMetadata(metadata);
        return this;
    }

    /**
     * Checkout Payment Settings Response
     */
    public OrdersClosedResponseBuilder checkouts(List<GetCheckoutPaymentResponse> checkouts) {
        ordersClosedResponse.setCheckouts(checkouts);
        return this;
    }

    /**
     * Ip address
     */
    public OrdersClosedResponseBuilder ip(String ip) {
        ordersClosedResponse.setIp(ip);
        return this;
    }

    /**
     * Session id
     */
    public OrdersClosedResponseBuilder sessionId(String sessionId) {
        ordersClosedResponse.setSessionId(sessionId);
        return this;
    }

    public OrdersClosedResponseBuilder location(Location location) {
        ordersClosedResponse.setLocation(location);
        return this;
    }

    public OrdersClosedResponseBuilder device(Device device) {
        ordersClosedResponse.setDevice(device);
        return this;
    }

    /**
     * Indicates whether the order is closed
     */
    public OrdersClosedResponseBuilder closed(boolean closed) {
        ordersClosedResponse.setClosed(closed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OrdersClosedResponse build() {
        return ordersClosedResponse;
    }
}