/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class OrdersResponse1Builder {
    //the instance to build
    private OrdersResponse1 ordersResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public OrdersResponse1Builder() {
        ordersResponse1 = new OrdersResponse1();
    }

    public OrdersResponse1Builder id(String id) {
        ordersResponse1.setId(id);
        return this;
    }

    public OrdersResponse1Builder code(String code) {
        ordersResponse1.setCode(code);
        return this;
    }

    public OrdersResponse1Builder currency(String currency) {
        ordersResponse1.setCurrency(currency);
        return this;
    }

    public OrdersResponse1Builder items(List<GetOrderItemResponse> items) {
        ordersResponse1.setItems(items);
        return this;
    }

    public OrdersResponse1Builder customer(Customer customer) {
        ordersResponse1.setCustomer(customer);
        return this;
    }

    public OrdersResponse1Builder status(String status) {
        ordersResponse1.setStatus(status);
        return this;
    }

    public OrdersResponse1Builder createdAt(DateTime createdAt) {
        ordersResponse1.setCreatedAt(createdAt);
        return this;
    }

    public OrdersResponse1Builder updatedAt(DateTime updatedAt) {
        ordersResponse1.setUpdatedAt(updatedAt);
        return this;
    }

    public OrdersResponse1Builder charges(List<GetChargeResponse> charges) {
        ordersResponse1.setCharges(charges);
        return this;
    }

    public OrdersResponse1Builder invoiceUrl(String invoiceUrl) {
        ordersResponse1.setInvoiceUrl(invoiceUrl);
        return this;
    }

    public OrdersResponse1Builder shipping(Shipping shipping) {
        ordersResponse1.setShipping(shipping);
        return this;
    }

    public OrdersResponse1Builder metadata(LinkedHashMap<String, String> metadata) {
        ordersResponse1.setMetadata(metadata);
        return this;
    }

    /**
     * Checkout Payment Settings Response
     */
    public OrdersResponse1Builder checkouts(List<GetCheckoutPaymentResponse> checkouts) {
        ordersResponse1.setCheckouts(checkouts);
        return this;
    }

    /**
     * Ip address
     */
    public OrdersResponse1Builder ip(String ip) {
        ordersResponse1.setIp(ip);
        return this;
    }

    /**
     * Session id
     */
    public OrdersResponse1Builder sessionId(String sessionId) {
        ordersResponse1.setSessionId(sessionId);
        return this;
    }

    public OrdersResponse1Builder location(Location location) {
        ordersResponse1.setLocation(location);
        return this;
    }

    public OrdersResponse1Builder device(Device device) {
        ordersResponse1.setDevice(device);
        return this;
    }

    /**
     * Indicates whether the order is closed
     */
    public OrdersResponse1Builder closed(boolean closed) {
        ordersResponse1.setClosed(closed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OrdersResponse1 build() {
        return ordersResponse1;
    }
}