/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class OrdersMetadataRequestBuilder {
    //the instance to build
    private OrdersMetadataRequest ordersMetadataRequest;

    /**
     * Default constructor to initialize the instance
     */
    public OrdersMetadataRequestBuilder() {
        ordersMetadataRequest = new OrdersMetadataRequest();
    }

    /**
     * Metadata
     */
    public OrdersMetadataRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        ordersMetadataRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OrdersMetadataRequest build() {
        return ordersMetadataRequest;
    }
}