/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PagingBuilder {
    //the instance to build
    private Paging paging;

    /**
     * Default constructor to initialize the instance
     */
    public PagingBuilder() {
        paging = new Paging();
    }

    /**
     * Total number of pages
     */
    public PagingBuilder total(int total) {
        paging.setTotal(total);
        return this;
    }

    /**
     * Previous page
     */
    public PagingBuilder previous(String previous) {
        paging.setPrevious(previous);
        return this;
    }

    /**
     * Next page
     */
    public PagingBuilder next(String next) {
        paging.setNext(next);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Paging build() {
        return paging;
    }
}