/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class PeriodBuilder {
    //the instance to build
    private Period period;

    /**
     * Default constructor to initialize the instance
     */
    public PeriodBuilder() {
        period = new Period();
    }

    public PeriodBuilder startAt(DateTime startAt) {
        period.setStartAt(startAt);
        return this;
    }

    public PeriodBuilder endAt(DateTime endAt) {
        period.setEndAt(endAt);
        return this;
    }

    public PeriodBuilder id(String id) {
        period.setId(id);
        return this;
    }

    public PeriodBuilder billingAt(DateTime billingAt) {
        period.setBillingAt(billingAt);
        return this;
    }

    public PeriodBuilder subscription(GetSubscriptionResponse subscription) {
        period.setSubscription(subscription);
        return this;
    }

    public PeriodBuilder status(String status) {
        period.setStatus(status);
        return this;
    }

    public PeriodBuilder duration(int duration) {
        period.setDuration(duration);
        return this;
    }

    public PeriodBuilder createdAt(String createdAt) {
        period.setCreatedAt(createdAt);
        return this;
    }

    public PeriodBuilder updatedAt(String updatedAt) {
        period.setUpdatedAt(updatedAt);
        return this;
    }

    public PeriodBuilder cycle(int cycle) {
        period.setCycle(cycle);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Period build() {
        return period;
    }
}