/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PlansResponseBuilder {
    //the instance to build
    private PlansResponse plansResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PlansResponseBuilder() {
        plansResponse = new PlansResponse();
    }

    /**
     * The plan objects
     */
    public PlansResponseBuilder data(List<GetPlanResponse> data) {
        plansResponse.setData(data);
        return this;
    }

    public PlansResponseBuilder paging(Paging paging) {
        plansResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlansResponse build() {
        return plansResponse;
    }
}