/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PlansMetadataRequestBuilder {
    //the instance to build
    private PlansMetadataRequest plansMetadataRequest;

    /**
     * Default constructor to initialize the instance
     */
    public PlansMetadataRequestBuilder() {
        plansMetadataRequest = new PlansMetadataRequest();
    }

    /**
     * Metadata
     */
    public PlansMetadataRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        plansMetadataRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlansMetadataRequest build() {
        return plansMetadataRequest;
    }
}