/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PlansItemsRequest1Builder {
    //the instance to build
    private PlansItemsRequest1 plansItemsRequest1;

    /**
     * Default constructor to initialize the instance
     */
    public PlansItemsRequest1Builder() {
        plansItemsRequest1 = new PlansItemsRequest1();
    }

    /**
     * Item name
     */
    public PlansItemsRequest1Builder name(String name) {
        plansItemsRequest1.setName(name);
        return this;
    }

    public PlansItemsRequest1Builder pricingScheme(PricingScheme4 pricingScheme) {
        plansItemsRequest1.setPricingScheme(pricingScheme);
        return this;
    }

    /**
     * Item's id
     */
    public PlansItemsRequest1Builder id(String id) {
        plansItemsRequest1.setId(id);
        return this;
    }

    /**
     * Item's description
     */
    public PlansItemsRequest1Builder description(String description) {
        plansItemsRequest1.setDescription(description);
        return this;
    }

    /**
     * Number of cycles where the item will be charged
     */
    public PlansItemsRequest1Builder cycles(Integer cycles) {
        plansItemsRequest1.setCycles(cycles);
        return this;
    }

    /**
     * Quantity
     */
    public PlansItemsRequest1Builder quantity(Integer quantity) {
        plansItemsRequest1.setQuantity(quantity);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlansItemsRequest1 build() {
        return plansItemsRequest1;
    }
}