/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class PlansMetadataResponseBuilder {
    //the instance to build
    private PlansMetadataResponse plansMetadataResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PlansMetadataResponseBuilder() {
        plansMetadataResponse = new PlansMetadataResponse();
    }

    public PlansMetadataResponseBuilder id(String id) {
        plansMetadataResponse.setId(id);
        return this;
    }

    public PlansMetadataResponseBuilder name(String name) {
        plansMetadataResponse.setName(name);
        return this;
    }

    public PlansMetadataResponseBuilder description(String description) {
        plansMetadataResponse.setDescription(description);
        return this;
    }

    public PlansMetadataResponseBuilder url(String url) {
        plansMetadataResponse.setUrl(url);
        return this;
    }

    public PlansMetadataResponseBuilder statementDescriptor(String statementDescriptor) {
        plansMetadataResponse.setStatementDescriptor(statementDescriptor);
        return this;
    }

    public PlansMetadataResponseBuilder interval(String interval) {
        plansMetadataResponse.setInterval(interval);
        return this;
    }

    public PlansMetadataResponseBuilder intervalCount(int intervalCount) {
        plansMetadataResponse.setIntervalCount(intervalCount);
        return this;
    }

    public PlansMetadataResponseBuilder billingType(String billingType) {
        plansMetadataResponse.setBillingType(billingType);
        return this;
    }

    public PlansMetadataResponseBuilder paymentMethods(List<String> paymentMethods) {
        plansMetadataResponse.setPaymentMethods(paymentMethods);
        return this;
    }

    public PlansMetadataResponseBuilder installments(List<Integer> installments) {
        plansMetadataResponse.setInstallments(installments);
        return this;
    }

    public PlansMetadataResponseBuilder status(String status) {
        plansMetadataResponse.setStatus(status);
        return this;
    }

    public PlansMetadataResponseBuilder currency(String currency) {
        plansMetadataResponse.setCurrency(currency);
        return this;
    }

    public PlansMetadataResponseBuilder createdAt(DateTime createdAt) {
        plansMetadataResponse.setCreatedAt(createdAt);
        return this;
    }

    public PlansMetadataResponseBuilder updatedAt(DateTime updatedAt) {
        plansMetadataResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public PlansMetadataResponseBuilder items(List<GetPlanItemResponse> items) {
        plansMetadataResponse.setItems(items);
        return this;
    }

    public PlansMetadataResponseBuilder billingDays(List<Integer> billingDays) {
        plansMetadataResponse.setBillingDays(billingDays);
        return this;
    }

    public PlansMetadataResponseBuilder shippable(boolean shippable) {
        plansMetadataResponse.setShippable(shippable);
        return this;
    }

    public PlansMetadataResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        plansMetadataResponse.setMetadata(metadata);
        return this;
    }

    public PlansMetadataResponseBuilder trialPeriodDays(Integer trialPeriodDays) {
        plansMetadataResponse.setTrialPeriodDays(trialPeriodDays);
        return this;
    }

    public PlansMetadataResponseBuilder minimumPrice(Integer minimumPrice) {
        plansMetadataResponse.setMinimumPrice(minimumPrice);
        return this;
    }

    public PlansMetadataResponseBuilder deletedAt(DateTime deletedAt) {
        plansMetadataResponse.setDeletedAt(deletedAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlansMetadataResponse build() {
        return plansMetadataResponse;
    }
}