/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class PlansItemsResponseBuilder {
    //the instance to build
    private PlansItemsResponse plansItemsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PlansItemsResponseBuilder() {
        plansItemsResponse = new PlansItemsResponse();
    }

    public PlansItemsResponseBuilder id(String id) {
        plansItemsResponse.setId(id);
        return this;
    }

    public PlansItemsResponseBuilder name(String name) {
        plansItemsResponse.setName(name);
        return this;
    }

    public PlansItemsResponseBuilder status(String status) {
        plansItemsResponse.setStatus(status);
        return this;
    }

    public PlansItemsResponseBuilder createdAt(DateTime createdAt) {
        plansItemsResponse.setCreatedAt(createdAt);
        return this;
    }

    public PlansItemsResponseBuilder updatedAt(DateTime updatedAt) {
        plansItemsResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public PlansItemsResponseBuilder pricingScheme(PricingScheme pricingScheme) {
        plansItemsResponse.setPricingScheme(pricingScheme);
        return this;
    }

    public PlansItemsResponseBuilder description(String description) {
        plansItemsResponse.setDescription(description);
        return this;
    }

    public PlansItemsResponseBuilder plan(Plan plan) {
        plansItemsResponse.setPlan(plan);
        return this;
    }

    public PlansItemsResponseBuilder quantity(Integer quantity) {
        plansItemsResponse.setQuantity(quantity);
        return this;
    }

    public PlansItemsResponseBuilder cycles(Integer cycles) {
        plansItemsResponse.setCycles(cycles);
        return this;
    }

    public PlansItemsResponseBuilder deletedAt(DateTime deletedAt) {
        plansItemsResponse.setDeletedAt(deletedAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PlansItemsResponse build() {
        return plansItemsResponse;
    }
}