/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PriceBracketBuilder {
    //the instance to build
    private PriceBracket priceBracket;

    /**
     * Default constructor to initialize the instance
     */
    public PriceBracketBuilder() {
        priceBracket = new PriceBracket();
    }

    public PriceBracketBuilder startQuantity(int startQuantity) {
        priceBracket.setStartQuantity(startQuantity);
        return this;
    }

    public PriceBracketBuilder price(int price) {
        priceBracket.setPrice(price);
        return this;
    }

    public PriceBracketBuilder endQuantity(Integer endQuantity) {
        priceBracket.setEndQuantity(endQuantity);
        return this;
    }

    public PriceBracketBuilder overagePrice(Integer overagePrice) {
        priceBracket.setOveragePrice(overagePrice);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PriceBracket build() {
        return priceBracket;
    }
}