/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PricingSchemeBuilder {
    //the instance to build
    private PricingScheme pricingScheme;

    /**
     * Default constructor to initialize the instance
     */
    public PricingSchemeBuilder() {
        pricingScheme = new PricingScheme();
    }

    public PricingSchemeBuilder price(int price) {
        pricingScheme.setPrice(price);
        return this;
    }

    public PricingSchemeBuilder schemeType(String schemeType) {
        pricingScheme.setSchemeType(schemeType);
        return this;
    }

    public PricingSchemeBuilder priceBrackets(List<GetPriceBracketResponse> priceBrackets) {
        pricingScheme.setPriceBrackets(priceBrackets);
        return this;
    }

    public PricingSchemeBuilder minimumPrice(Integer minimumPrice) {
        pricingScheme.setMinimumPrice(minimumPrice);
        return this;
    }

    /**
     * percentual value used in pricing_scheme Percent
     */
    public PricingSchemeBuilder percentage(Double percentage) {
        pricingScheme.setPercentage(percentage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PricingScheme build() {
        return pricingScheme;
    }
}