/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class PricingScheme3Builder {
    //the instance to build
    private PricingScheme3 pricingScheme3;

    /**
     * Default constructor to initialize the instance
     */
    public PricingScheme3Builder() {
        pricingScheme3 = new PricingScheme3();
    }

    /**
     * Scheme type
     */
    public PricingScheme3Builder schemeType(String schemeType) {
        pricingScheme3.setSchemeType(schemeType);
        return this;
    }

    /**
     * Price brackets
     */
    public PricingScheme3Builder priceBrackets(List<UpdatePriceBracketRequest> priceBrackets) {
        pricingScheme3.setPriceBrackets(priceBrackets);
        return this;
    }

    /**
     * Price
     */
    public PricingScheme3Builder price(Integer price) {
        pricingScheme3.setPrice(price);
        return this;
    }

    /**
     * Minimum price
     */
    public PricingScheme3Builder minimumPrice(Integer minimumPrice) {
        pricingScheme3.setMinimumPrice(minimumPrice);
        return this;
    }

    /**
     * percentual value used in pricing_scheme Percent
     */
    public PricingScheme3Builder percentage(Double percentage) {
        pricingScheme3.setPercentage(percentage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PricingScheme3 build() {
        return pricingScheme3;
    }
}