/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsResponseBuilder {
    //the instance to build
    private RecipientsResponse recipientsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsResponseBuilder() {
        recipientsResponse = new RecipientsResponse();
    }

    /**
     * Recipients
     */
    public RecipientsResponseBuilder data(List<GetRecipientResponse> data) {
        recipientsResponse.setData(data);
        return this;
    }

    public RecipientsResponseBuilder paging(Paging paging) {
        recipientsResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsResponse build() {
        return recipientsResponse;
    }
}