/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class RecipientBuilder {
    //the instance to build
    private Recipient recipient;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientBuilder() {
        recipient = new Recipient();
    }

    /**
     * Id
     */
    public RecipientBuilder id(String id) {
        recipient.setId(id);
        return this;
    }

    /**
     * Name
     */
    public RecipientBuilder name(String name) {
        recipient.setName(name);
        return this;
    }

    /**
     * Email
     */
    public RecipientBuilder email(String email) {
        recipient.setEmail(email);
        return this;
    }

    /**
     * Document
     */
    public RecipientBuilder document(String document) {
        recipient.setDocument(document);
        return this;
    }

    /**
     * Description
     */
    public RecipientBuilder description(String description) {
        recipient.setDescription(description);
        return this;
    }

    /**
     * Type
     */
    public RecipientBuilder type(String type) {
        recipient.setType(type);
        return this;
    }

    /**
     * Status
     */
    public RecipientBuilder status(String status) {
        recipient.setStatus(status);
        return this;
    }

    /**
     * Creation date
     */
    public RecipientBuilder createdAt(DateTime createdAt) {
        recipient.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Last update date
     */
    public RecipientBuilder updatedAt(DateTime updatedAt) {
        recipient.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * Deletion date
     */
    public RecipientBuilder deletedAt(DateTime deletedAt) {
        recipient.setDeletedAt(deletedAt);
        return this;
    }

    public RecipientBuilder defaultBankAccount(DefaultBankAccount defaultBankAccount) {
        recipient.setDefaultBankAccount(defaultBankAccount);
        return this;
    }

    /**
     * Info about the recipient on the gateway
     */
    public RecipientBuilder gatewayRecipients(List<GetGatewayRecipientResponse> gatewayRecipients) {
        recipient.setGatewayRecipients(gatewayRecipients);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientBuilder metadata(LinkedHashMap<String, String> metadata) {
        recipient.setMetadata(metadata);
        return this;
    }

    public RecipientBuilder automaticAnticipationSettings(CreateAutomaticAnticipationSettingsRequest automaticAnticipationSettings) {
        recipient.setAutomaticAnticipationSettings(automaticAnticipationSettings);
        return this;
    }

    public RecipientBuilder transferSettings(GetTransferSettingsResponse transferSettings) {
        recipient.setTransferSettings(transferSettings);
        return this;
    }

    /**
     * Recipient code
     */
    public RecipientBuilder code(String code) {
        recipient.setCode(code);
        return this;
    }

    /**
     * Payment mode
     */
    public RecipientBuilder paymentMode(String paymentMode) {
        recipient.setPaymentMode(paymentMode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Recipient build() {
        return recipient;
    }
}