/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class RecipientsResponse1Builder {
    //the instance to build
    private RecipientsResponse1 recipientsResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsResponse1Builder() {
        recipientsResponse1 = new RecipientsResponse1();
    }

    /**
     * Id
     */
    public RecipientsResponse1Builder id(String id) {
        recipientsResponse1.setId(id);
        return this;
    }

    /**
     * Name
     */
    public RecipientsResponse1Builder name(String name) {
        recipientsResponse1.setName(name);
        return this;
    }

    /**
     * Email
     */
    public RecipientsResponse1Builder email(String email) {
        recipientsResponse1.setEmail(email);
        return this;
    }

    /**
     * Document
     */
    public RecipientsResponse1Builder document(String document) {
        recipientsResponse1.setDocument(document);
        return this;
    }

    /**
     * Description
     */
    public RecipientsResponse1Builder description(String description) {
        recipientsResponse1.setDescription(description);
        return this;
    }

    /**
     * Type
     */
    public RecipientsResponse1Builder type(String type) {
        recipientsResponse1.setType(type);
        return this;
    }

    /**
     * Status
     */
    public RecipientsResponse1Builder status(String status) {
        recipientsResponse1.setStatus(status);
        return this;
    }

    /**
     * Creation date
     */
    public RecipientsResponse1Builder createdAt(DateTime createdAt) {
        recipientsResponse1.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Last update date
     */
    public RecipientsResponse1Builder updatedAt(DateTime updatedAt) {
        recipientsResponse1.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * Deletion date
     */
    public RecipientsResponse1Builder deletedAt(DateTime deletedAt) {
        recipientsResponse1.setDeletedAt(deletedAt);
        return this;
    }

    public RecipientsResponse1Builder defaultBankAccount(DefaultBankAccount defaultBankAccount) {
        recipientsResponse1.setDefaultBankAccount(defaultBankAccount);
        return this;
    }

    /**
     * Info about the recipient on the gateway
     */
    public RecipientsResponse1Builder gatewayRecipients(List<GetGatewayRecipientResponse> gatewayRecipients) {
        recipientsResponse1.setGatewayRecipients(gatewayRecipients);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientsResponse1Builder metadata(LinkedHashMap<String, String> metadata) {
        recipientsResponse1.setMetadata(metadata);
        return this;
    }

    public RecipientsResponse1Builder automaticAnticipationSettings(CreateAutomaticAnticipationSettingsRequest automaticAnticipationSettings) {
        recipientsResponse1.setAutomaticAnticipationSettings(automaticAnticipationSettings);
        return this;
    }

    public RecipientsResponse1Builder transferSettings(GetTransferSettingsResponse transferSettings) {
        recipientsResponse1.setTransferSettings(transferSettings);
        return this;
    }

    /**
     * Recipient code
     */
    public RecipientsResponse1Builder code(String code) {
        recipientsResponse1.setCode(code);
        return this;
    }

    /**
     * Payment mode
     */
    public RecipientsResponse1Builder paymentMode(String paymentMode) {
        recipientsResponse1.setPaymentMode(paymentMode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsResponse1 build() {
        return recipientsResponse1;
    }
}