/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsBalanceResponseBuilder {
    //the instance to build
    private RecipientsBalanceResponse recipientsBalanceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsBalanceResponseBuilder() {
        recipientsBalanceResponse = new RecipientsBalanceResponse();
    }

    /**
     * Currency
     */
    public RecipientsBalanceResponseBuilder currency(String currency) {
        recipientsBalanceResponse.setCurrency(currency);
        return this;
    }

    /**
     * Amount available for transferring
     */
    public RecipientsBalanceResponseBuilder availableAmount(long availableAmount) {
        recipientsBalanceResponse.setAvailableAmount(availableAmount);
        return this;
    }

    public RecipientsBalanceResponseBuilder recipient(Recipient recipient) {
        recipientsBalanceResponse.setRecipient(recipient);
        return this;
    }

    public RecipientsBalanceResponseBuilder waitingFundsAmount(long waitingFundsAmount) {
        recipientsBalanceResponse.setWaitingFundsAmount(waitingFundsAmount);
        return this;
    }

    public RecipientsBalanceResponseBuilder transferredAmount(long transferredAmount) {
        recipientsBalanceResponse.setTransferredAmount(transferredAmount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsBalanceResponse build() {
        return recipientsBalanceResponse;
    }
}