/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsAnticipationLimitsResponseBuilder {
    //the instance to build
    private RecipientsAnticipationLimitsResponse recipientsAnticipationLimitsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsAnticipationLimitsResponseBuilder() {
        recipientsAnticipationLimitsResponse = new RecipientsAnticipationLimitsResponse();
    }

    /**
     * Amount
     */
    public RecipientsAnticipationLimitsResponseBuilder amount(int amount) {
        recipientsAnticipationLimitsResponse.setAmount(amount);
        return this;
    }

    /**
     * Anticipation fee
     */
    public RecipientsAnticipationLimitsResponseBuilder anticipationFee(int anticipationFee) {
        recipientsAnticipationLimitsResponse.setAnticipationFee(anticipationFee);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsAnticipationLimitsResponse build() {
        return recipientsAnticipationLimitsResponse;
    }
}