/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class RecipientsDefaultBankAccountResponseBuilder {
    //the instance to build
    private RecipientsDefaultBankAccountResponse recipientsDefaultBankAccountResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsDefaultBankAccountResponseBuilder() {
        recipientsDefaultBankAccountResponse = new RecipientsDefaultBankAccountResponse();
    }

    /**
     * Id
     */
    public RecipientsDefaultBankAccountResponseBuilder id(String id) {
        recipientsDefaultBankAccountResponse.setId(id);
        return this;
    }

    /**
     * Name
     */
    public RecipientsDefaultBankAccountResponseBuilder name(String name) {
        recipientsDefaultBankAccountResponse.setName(name);
        return this;
    }

    /**
     * Email
     */
    public RecipientsDefaultBankAccountResponseBuilder email(String email) {
        recipientsDefaultBankAccountResponse.setEmail(email);
        return this;
    }

    /**
     * Document
     */
    public RecipientsDefaultBankAccountResponseBuilder document(String document) {
        recipientsDefaultBankAccountResponse.setDocument(document);
        return this;
    }

    /**
     * Description
     */
    public RecipientsDefaultBankAccountResponseBuilder description(String description) {
        recipientsDefaultBankAccountResponse.setDescription(description);
        return this;
    }

    /**
     * Type
     */
    public RecipientsDefaultBankAccountResponseBuilder type(String type) {
        recipientsDefaultBankAccountResponse.setType(type);
        return this;
    }

    /**
     * Status
     */
    public RecipientsDefaultBankAccountResponseBuilder status(String status) {
        recipientsDefaultBankAccountResponse.setStatus(status);
        return this;
    }

    /**
     * Creation date
     */
    public RecipientsDefaultBankAccountResponseBuilder createdAt(DateTime createdAt) {
        recipientsDefaultBankAccountResponse.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Last update date
     */
    public RecipientsDefaultBankAccountResponseBuilder updatedAt(DateTime updatedAt) {
        recipientsDefaultBankAccountResponse.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * Deletion date
     */
    public RecipientsDefaultBankAccountResponseBuilder deletedAt(DateTime deletedAt) {
        recipientsDefaultBankAccountResponse.setDeletedAt(deletedAt);
        return this;
    }

    public RecipientsDefaultBankAccountResponseBuilder defaultBankAccount(DefaultBankAccount defaultBankAccount) {
        recipientsDefaultBankAccountResponse.setDefaultBankAccount(defaultBankAccount);
        return this;
    }

    /**
     * Info about the recipient on the gateway
     */
    public RecipientsDefaultBankAccountResponseBuilder gatewayRecipients(List<GetGatewayRecipientResponse> gatewayRecipients) {
        recipientsDefaultBankAccountResponse.setGatewayRecipients(gatewayRecipients);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientsDefaultBankAccountResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        recipientsDefaultBankAccountResponse.setMetadata(metadata);
        return this;
    }

    public RecipientsDefaultBankAccountResponseBuilder automaticAnticipationSettings(CreateAutomaticAnticipationSettingsRequest automaticAnticipationSettings) {
        recipientsDefaultBankAccountResponse.setAutomaticAnticipationSettings(automaticAnticipationSettings);
        return this;
    }

    public RecipientsDefaultBankAccountResponseBuilder transferSettings(GetTransferSettingsResponse transferSettings) {
        recipientsDefaultBankAccountResponse.setTransferSettings(transferSettings);
        return this;
    }

    /**
     * Recipient code
     */
    public RecipientsDefaultBankAccountResponseBuilder code(String code) {
        recipientsDefaultBankAccountResponse.setCode(code);
        return this;
    }

    /**
     * Payment mode
     */
    public RecipientsDefaultBankAccountResponseBuilder paymentMode(String paymentMode) {
        recipientsDefaultBankAccountResponse.setPaymentMode(paymentMode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsDefaultBankAccountResponse build() {
        return recipientsDefaultBankAccountResponse;
    }
}