/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsRequest1Builder {
    //the instance to build
    private RecipientsRequest1 recipientsRequest1;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsRequest1Builder() {
        recipientsRequest1 = new RecipientsRequest1();
    }

    /**
     * Name
     */
    public RecipientsRequest1Builder name(String name) {
        recipientsRequest1.setName(name);
        return this;
    }

    /**
     * Email
     */
    public RecipientsRequest1Builder email(String email) {
        recipientsRequest1.setEmail(email);
        return this;
    }

    /**
     * Description
     */
    public RecipientsRequest1Builder description(String description) {
        recipientsRequest1.setDescription(description);
        return this;
    }

    /**
     * Type
     */
    public RecipientsRequest1Builder type(String type) {
        recipientsRequest1.setType(type);
        return this;
    }

    /**
     * Status
     */
    public RecipientsRequest1Builder status(String status) {
        recipientsRequest1.setStatus(status);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientsRequest1Builder metadata(LinkedHashMap<String, String> metadata) {
        recipientsRequest1.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsRequest1 build() {
        return recipientsRequest1;
    }
}