/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class RecipientsMetadataResponseBuilder {
    //the instance to build
    private RecipientsMetadataResponse recipientsMetadataResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsMetadataResponseBuilder() {
        recipientsMetadataResponse = new RecipientsMetadataResponse();
    }

    /**
     * Id
     */
    public RecipientsMetadataResponseBuilder id(String id) {
        recipientsMetadataResponse.setId(id);
        return this;
    }

    /**
     * Name
     */
    public RecipientsMetadataResponseBuilder name(String name) {
        recipientsMetadataResponse.setName(name);
        return this;
    }

    /**
     * Email
     */
    public RecipientsMetadataResponseBuilder email(String email) {
        recipientsMetadataResponse.setEmail(email);
        return this;
    }

    /**
     * Document
     */
    public RecipientsMetadataResponseBuilder document(String document) {
        recipientsMetadataResponse.setDocument(document);
        return this;
    }

    /**
     * Description
     */
    public RecipientsMetadataResponseBuilder description(String description) {
        recipientsMetadataResponse.setDescription(description);
        return this;
    }

    /**
     * Type
     */
    public RecipientsMetadataResponseBuilder type(String type) {
        recipientsMetadataResponse.setType(type);
        return this;
    }

    /**
     * Status
     */
    public RecipientsMetadataResponseBuilder status(String status) {
        recipientsMetadataResponse.setStatus(status);
        return this;
    }

    /**
     * Creation date
     */
    public RecipientsMetadataResponseBuilder createdAt(DateTime createdAt) {
        recipientsMetadataResponse.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Last update date
     */
    public RecipientsMetadataResponseBuilder updatedAt(DateTime updatedAt) {
        recipientsMetadataResponse.setUpdatedAt(updatedAt);
        return this;
    }

    /**
     * Deletion date
     */
    public RecipientsMetadataResponseBuilder deletedAt(DateTime deletedAt) {
        recipientsMetadataResponse.setDeletedAt(deletedAt);
        return this;
    }

    public RecipientsMetadataResponseBuilder defaultBankAccount(DefaultBankAccount defaultBankAccount) {
        recipientsMetadataResponse.setDefaultBankAccount(defaultBankAccount);
        return this;
    }

    /**
     * Info about the recipient on the gateway
     */
    public RecipientsMetadataResponseBuilder gatewayRecipients(List<GetGatewayRecipientResponse> gatewayRecipients) {
        recipientsMetadataResponse.setGatewayRecipients(gatewayRecipients);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientsMetadataResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        recipientsMetadataResponse.setMetadata(metadata);
        return this;
    }

    public RecipientsMetadataResponseBuilder automaticAnticipationSettings(CreateAutomaticAnticipationSettingsRequest automaticAnticipationSettings) {
        recipientsMetadataResponse.setAutomaticAnticipationSettings(automaticAnticipationSettings);
        return this;
    }

    public RecipientsMetadataResponseBuilder transferSettings(GetTransferSettingsResponse transferSettings) {
        recipientsMetadataResponse.setTransferSettings(transferSettings);
        return this;
    }

    /**
     * Recipient code
     */
    public RecipientsMetadataResponseBuilder code(String code) {
        recipientsMetadataResponse.setCode(code);
        return this;
    }

    /**
     * Payment mode
     */
    public RecipientsMetadataResponseBuilder paymentMode(String paymentMode) {
        recipientsMetadataResponse.setPaymentMode(paymentMode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsMetadataResponse build() {
        return recipientsMetadataResponse;
    }
}