/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsAnticipationsResponse1Builder {
    //the instance to build
    private RecipientsAnticipationsResponse1 recipientsAnticipationsResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsAnticipationsResponse1Builder() {
        recipientsAnticipationsResponse1 = new RecipientsAnticipationsResponse1();
    }

    /**
     * Anticipations
     */
    public RecipientsAnticipationsResponse1Builder data(List<GetAnticipationResponse> data) {
        recipientsAnticipationsResponse1.setData(data);
        return this;
    }

    public RecipientsAnticipationsResponse1Builder paging(Paging paging) {
        recipientsAnticipationsResponse1.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsAnticipationsResponse1 build() {
        return recipientsAnticipationsResponse1;
    }
}