/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class RecipientsRequestBuilder {
    //the instance to build
    private RecipientsRequest recipientsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsRequestBuilder() {
        recipientsRequest = new RecipientsRequest();
    }

    /**
     * Recipient name
     */
    public RecipientsRequestBuilder name(String name) {
        recipientsRequest.setName(name);
        return this;
    }

    /**
     * Recipient email
     */
    public RecipientsRequestBuilder email(String email) {
        recipientsRequest.setEmail(email);
        return this;
    }

    /**
     * Recipient description
     */
    public RecipientsRequestBuilder description(String description) {
        recipientsRequest.setDescription(description);
        return this;
    }

    /**
     * Recipient document number
     */
    public RecipientsRequestBuilder document(String document) {
        recipientsRequest.setDocument(document);
        return this;
    }

    /**
     * Recipient type
     */
    public RecipientsRequestBuilder type(String type) {
        recipientsRequest.setType(type);
        return this;
    }

    public RecipientsRequestBuilder defaultBankAccount(DefaultBankAccount1 defaultBankAccount) {
        recipientsRequest.setDefaultBankAccount(defaultBankAccount);
        return this;
    }

    /**
     * Metadata
     */
    public RecipientsRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        recipientsRequest.setMetadata(metadata);
        return this;
    }

    public RecipientsRequestBuilder transferSettings(GetTransferSettingsResponse transferSettings) {
        recipientsRequest.setTransferSettings(transferSettings);
        return this;
    }

    /**
     * Recipient code
     */
    public RecipientsRequestBuilder code(String code) {
        recipientsRequest.setCode(code);
        return this;
    }

    /**
     * Payment mode
     */
    public RecipientsRequestBuilder paymentMode(String paymentMode) {
        recipientsRequest.setPaymentMode(paymentMode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsRequest build() {
        return recipientsRequest;
    }
}