/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class RecipientsAnticipationsRequestBuilder {
    //the instance to build
    private RecipientsAnticipationsRequest recipientsAnticipationsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RecipientsAnticipationsRequestBuilder() {
        recipientsAnticipationsRequest = new RecipientsAnticipationsRequest();
    }

    /**
     * Amount requested for the anticipation
     */
    public RecipientsAnticipationsRequestBuilder amount(int amount) {
        recipientsAnticipationsRequest.setAmount(amount);
        return this;
    }

    /**
     * Timeframe
     */
    public RecipientsAnticipationsRequestBuilder timeframe(String timeframe) {
        recipientsAnticipationsRequest.setTimeframe(timeframe);
        return this;
    }

    /**
     * Payment date
     */
    public RecipientsAnticipationsRequestBuilder paymentDate(DateTime paymentDate) {
        recipientsAnticipationsRequest.setPaymentDate(paymentDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RecipientsAnticipationsRequest build() {
        return recipientsAnticipationsRequest;
    }
}