/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SetupBuilder {
    //the instance to build
    private Setup setup;

    /**
     * Default constructor to initialize the instance
     */
    public SetupBuilder() {
        setup = new Setup();
    }

    public SetupBuilder id(String id) {
        setup.setId(id);
        return this;
    }

    public SetupBuilder description(String description) {
        setup.setDescription(description);
        return this;
    }

    public SetupBuilder amount(int amount) {
        setup.setAmount(amount);
        return this;
    }

    public SetupBuilder status(String status) {
        setup.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Setup build() {
        return setup;
    }
}