/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SplitBuilder {
    //the instance to build
    private Split split;

    /**
     * Default constructor to initialize the instance
     */
    public SplitBuilder() {
        split = new Split();
    }

    /**
     * Defines if the split is enabled
     */
    public SplitBuilder enabled(boolean enabled) {
        split.setEnabled(enabled);
        return this;
    }

    /**
     * Split
     */
    public SplitBuilder rules(List<GetSplitResponse> rules) {
        split.setRules(rules);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Split build() {
        return split;
    }
}