/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Split 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8383375886666719798L;
    private boolean enabled;
    private List<GetSplitResponse> rules;
    /** GETTER
     * Defines if the split is enabled
     */
    @JsonGetter("enabled")
    public boolean getEnabled ( ) { 
        return this.enabled;
    }
    
    /** SETTER
     * Defines if the split is enabled
     */
    @JsonSetter("enabled")
    public void setEnabled (boolean value) { 
        this.enabled = value;
    }
 
    /** GETTER
     * Split
     */
    @JsonGetter("rules")
    public List<GetSplitResponse> getRules ( ) { 
        return this.rules;
    }
    
    /** SETTER
     * Split
     */
    @JsonSetter("rules")
    public void setRules (List<GetSplitResponse> value) { 
        this.rules = value;
    }
 
}
