/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class SubscriptionsStartAtRequestBuilder {
    //the instance to build
    private SubscriptionsStartAtRequest subscriptionsStartAtRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsStartAtRequestBuilder() {
        subscriptionsStartAtRequest = new SubscriptionsStartAtRequest();
    }

    /**
     * The date when the subscription periods will start
     */
    public SubscriptionsStartAtRequestBuilder startAt(DateTime startAt) {
        subscriptionsStartAtRequest.setStartAt(startAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsStartAtRequest build() {
        return subscriptionsStartAtRequest;
    }
}