/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class SubscriptionsBillingDateRequestBuilder {
    //the instance to build
    private SubscriptionsBillingDateRequest subscriptionsBillingDateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsBillingDateRequestBuilder() {
        subscriptionsBillingDateRequest = new SubscriptionsBillingDateRequest();
    }

    /**
     * The date when the next subscription billing must occur
     */
    public SubscriptionsBillingDateRequestBuilder nextBillingAt(DateTime nextBillingAt) {
        subscriptionsBillingDateRequest.setNextBillingAt(nextBillingAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsBillingDateRequest build() {
        return subscriptionsBillingDateRequest;
    }
}