/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsItemsUsagesResponse1Builder {
    //the instance to build
    private SubscriptionsItemsUsagesResponse1 subscriptionsItemsUsagesResponse1;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsItemsUsagesResponse1Builder() {
        subscriptionsItemsUsagesResponse1 = new SubscriptionsItemsUsagesResponse1();
    }

    /**
     * The usage objects
     */
    public SubscriptionsItemsUsagesResponse1Builder data(List<GetUsageResponse> data) {
        subscriptionsItemsUsagesResponse1.setData(data);
        return this;
    }

    public SubscriptionsItemsUsagesResponse1Builder paging(Paging paging) {
        subscriptionsItemsUsagesResponse1.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsItemsUsagesResponse1 build() {
        return subscriptionsItemsUsagesResponse1;
    }
}