/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsItemsResponse3Builder {
    //the instance to build
    private SubscriptionsItemsResponse3 subscriptionsItemsResponse3;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsItemsResponse3Builder() {
        subscriptionsItemsResponse3 = new SubscriptionsItemsResponse3();
    }

    /**
     * The subscription items
     */
    public SubscriptionsItemsResponse3Builder data(List<GetSubscriptionItemResponse> data) {
        subscriptionsItemsResponse3.setData(data);
        return this;
    }

    public SubscriptionsItemsResponse3Builder paging(Paging paging) {
        subscriptionsItemsResponse3.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsItemsResponse3 build() {
        return subscriptionsItemsResponse3;
    }
}