/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsMinimumPriceRequestBuilder {
    //the instance to build
    private SubscriptionsMinimumPriceRequest subscriptionsMinimumPriceRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsMinimumPriceRequestBuilder() {
        subscriptionsMinimumPriceRequest = new SubscriptionsMinimumPriceRequest();
    }

    /**
     * Valor mínimo da assinatura
     */
    public SubscriptionsMinimumPriceRequestBuilder minimumPrice(Integer minimumPrice) {
        subscriptionsMinimumPriceRequest.setMinimumPrice(minimumPrice);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsMinimumPriceRequest build() {
        return subscriptionsMinimumPriceRequest;
    }
}