/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsResponse3Builder {
    //the instance to build
    private SubscriptionsResponse3 subscriptionsResponse3;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsResponse3Builder() {
        subscriptionsResponse3 = new SubscriptionsResponse3();
    }

    /**
     * The subscription objects
     */
    public SubscriptionsResponse3Builder data(List<GetSubscriptionResponse> data) {
        subscriptionsResponse3.setData(data);
        return this;
    }

    public SubscriptionsResponse3Builder paging(Paging paging) {
        subscriptionsResponse3.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsResponse3 build() {
        return subscriptionsResponse3;
    }
}