/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsCardRequestBuilder {
    //the instance to build
    private SubscriptionsCardRequest subscriptionsCardRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsCardRequestBuilder() {
        subscriptionsCardRequest = new SubscriptionsCardRequest();
    }

    public SubscriptionsCardRequestBuilder card(Card1 card) {
        subscriptionsCardRequest.setCard(card);
        return this;
    }

    /**
     * Credit card id
     */
    public SubscriptionsCardRequestBuilder cardId(String cardId) {
        subscriptionsCardRequest.setCardId(cardId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsCardRequest build() {
        return subscriptionsCardRequest;
    }
}