/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsCyclesResponse2Builder {
    //the instance to build
    private SubscriptionsCyclesResponse2 subscriptionsCyclesResponse2;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsCyclesResponse2Builder() {
        subscriptionsCyclesResponse2 = new SubscriptionsCyclesResponse2();
    }

    /**
     * The subscription cycles objects
     */
    public SubscriptionsCyclesResponse2Builder data(List<GetPeriodResponse> data) {
        subscriptionsCyclesResponse2.setData(data);
        return this;
    }

    public SubscriptionsCyclesResponse2Builder paging(Paging paging) {
        subscriptionsCyclesResponse2.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsCyclesResponse2 build() {
        return subscriptionsCyclesResponse2;
    }
}