/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class SubscriptionsMetadataRequestBuilder {
    //the instance to build
    private SubscriptionsMetadataRequest subscriptionsMetadataRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsMetadataRequestBuilder() {
        subscriptionsMetadataRequest = new SubscriptionsMetadataRequest();
    }

    /**
     * Metadata
     */
    public SubscriptionsMetadataRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        subscriptionsMetadataRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsMetadataRequest build() {
        return subscriptionsMetadataRequest;
    }
}