/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class SubscriptionsIncrementsResponseBuilder {
    //the instance to build
    private SubscriptionsIncrementsResponse subscriptionsIncrementsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsIncrementsResponseBuilder() {
        subscriptionsIncrementsResponse = new SubscriptionsIncrementsResponse();
    }

    public SubscriptionsIncrementsResponseBuilder id(String id) {
        subscriptionsIncrementsResponse.setId(id);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder value(double value) {
        subscriptionsIncrementsResponse.setValue(value);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder incrementType(String incrementType) {
        subscriptionsIncrementsResponse.setIncrementType(incrementType);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder status(String status) {
        subscriptionsIncrementsResponse.setStatus(status);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder createdAt(DateTime createdAt) {
        subscriptionsIncrementsResponse.setCreatedAt(createdAt);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder cycles(Integer cycles) {
        subscriptionsIncrementsResponse.setCycles(cycles);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder deletedAt(DateTime deletedAt) {
        subscriptionsIncrementsResponse.setDeletedAt(deletedAt);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder description(String description) {
        subscriptionsIncrementsResponse.setDescription(description);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder subscription(GetSubscriptionResponse subscription) {
        subscriptionsIncrementsResponse.setSubscription(subscription);
        return this;
    }

    public SubscriptionsIncrementsResponseBuilder subscriptionItem(GetSubscriptionItemResponse subscriptionItem) {
        subscriptionsIncrementsResponse.setSubscriptionItem(subscriptionItem);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsIncrementsResponse build() {
        return subscriptionsIncrementsResponse;
    }
}