/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class SubscriptionsItemsUsagesUsageIdResponseBuilder {
    //the instance to build
    private SubscriptionsItemsUsagesUsageIdResponse subscriptionsItemsUsagesUsageIdResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder() {
        subscriptionsItemsUsagesUsageIdResponse = new SubscriptionsItemsUsagesUsageIdResponse();
    }

    /**
     * Id
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder id(String id) {
        subscriptionsItemsUsagesUsageIdResponse.setId(id);
        return this;
    }

    /**
     * Quantity
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder quantity(int quantity) {
        subscriptionsItemsUsagesUsageIdResponse.setQuantity(quantity);
        return this;
    }

    /**
     * Description
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder description(String description) {
        subscriptionsItemsUsagesUsageIdResponse.setDescription(description);
        return this;
    }

    /**
     * Used at
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder usedAt(DateTime usedAt) {
        subscriptionsItemsUsagesUsageIdResponse.setUsedAt(usedAt);
        return this;
    }

    /**
     * Creation date
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder createdAt(DateTime createdAt) {
        subscriptionsItemsUsagesUsageIdResponse.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Status
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder status(String status) {
        subscriptionsItemsUsagesUsageIdResponse.setStatus(status);
        return this;
    }

    public SubscriptionsItemsUsagesUsageIdResponseBuilder deletedAt(DateTime deletedAt) {
        subscriptionsItemsUsagesUsageIdResponse.setDeletedAt(deletedAt);
        return this;
    }

    public SubscriptionsItemsUsagesUsageIdResponseBuilder subscriptionItem(GetSubscriptionItemResponse subscriptionItem) {
        subscriptionsItemsUsagesUsageIdResponse.setSubscriptionItem(subscriptionItem);
        return this;
    }

    /**
     * Identification code in the client system
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder code(String code) {
        subscriptionsItemsUsagesUsageIdResponse.setCode(code);
        return this;
    }

    /**
     * Identification group in the client system
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder group(String group) {
        subscriptionsItemsUsagesUsageIdResponse.setGroup(group);
        return this;
    }

    /**
     * Field used in item scheme type 'Percent'
     */
    public SubscriptionsItemsUsagesUsageIdResponseBuilder amount(Integer amount) {
        subscriptionsItemsUsagesUsageIdResponse.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionsItemsUsagesUsageIdResponse build() {
        return subscriptionsItemsUsagesUsageIdResponse;
    }
}