/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class UsagesBuilder {
    //the instance to build
    private Usages usages;

    /**
     * Default constructor to initialize the instance
     */
    public UsagesBuilder() {
        usages = new Usages();
    }

    /**
     * The usage objects
     */
    public UsagesBuilder data(List<GetUsageResponse> data) {
        usages.setData(data);
        return this;
    }

    public UsagesBuilder paging(Paging paging) {
        usages.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Usages build() {
        return usages;
    }
}