/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;

public class VoucherBuilder {
    //the instance to build
    private Voucher voucher;

    /**
     * Default constructor to initialize the instance
     */
    public VoucherBuilder() {
        voucher = new Voucher();
    }

    /**
     * The text that will be shown on the voucher's statement
     */
    public VoucherBuilder statementDescriptor(String statementDescriptor) {
        voucher.setStatementDescriptor(statementDescriptor);
        return this;
    }

    /**
     * Card id
     */
    public VoucherBuilder cardId(String cardId) {
        voucher.setCardId(cardId);
        return this;
    }

    /**
     * Card token
     */
    public VoucherBuilder cardToken(String cardToken) {
        voucher.setCardToken(cardToken);
        return this;
    }

    public VoucherBuilder card(Card1 card) {
        voucher.setCard(card);
        return this;
    }

    /**
     * Defines whether the card has been used one or more times.
     */
    public VoucherBuilder recurrencyCycle(String recurrencyCycle) {
        voucher.setRecurrencyCycle(recurrencyCycle);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Voucher build() {
        return voucher;
    }
}